# -*- coding: utf-8 -*-
"""fountains_exp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uh04RIMvtk73PBI8RyQiQFFQb2yLdIx7
"""

pip install cooltools

!pip install -U gprofiler-official

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os
from scipy.optimize import least_squares
from tqdm.auto import tqdm
import re
from scipy.optimize import least_squares
from scipy.special import erf

from google.colab import drive
drive.mount('/content/drive')

import cooltools
data_dir = './drive/MyDrive/fountains/data/'
import cooler

import sys
LIB_DIR = "./drive/MyDrive/fountains/"

if LIB_DIR not in sys.path:
    sys.path.append(LIB_DIR)

import fountain_tools_clean as ft

import importlib
importlib.reload(ft)

mcool_path_danio = "drive/MyDrive/fountains/data/GSE195609_Wild-Type_5.3.1000.mcool"
mcool_path_xenopus = "drive/MyDrive/fountains/data/stage11.xenTro10.mapq_30.1000.mcool"
mcool_path_madoka = "drive/MyDrive/fountains/data/HiC_st10.oryLat2.mapq_30.1000.mcool"
fountains_path_danio = "drive/MyDrive/fountains/fountains.csv"
fountains_path_xenopus ="drive/MyDrive/fountains/fountains_xenopus.csv"
fountains_path_madoka =  "drive/MyDrive/fountains/fountains_madoka.csv"
padre_path_danio = "drive/MyDrive/fountains/PADRE_DOME.csv"
baranasik_path_danio = "drive/MyDrive/fountains/baranasik.csv"
genes_path_danio = "drive/MyDrive/fountains/data/genomic.gtf"
cooler.fileops.list_coolers(mcool_path_xenopus)

"""# Проверки работы"""

res = 5000
clr = cooler.Cooler(f"{mcool_path_madoka}::resolutions/{res}")

print(clr)
print("binsize:", clr.binsize)
print("chromosomes:", clr.chromnames[:10])
print(clr.info)



region = "Chr6:26780000-27190000"

mat = clr.matrix(balance=False).fetch(region)
mat.shape

import matplotlib.pyplot as plt
import numpy as np

mat = clr.matrix(balance=False).fetch(region)

plt.figure(figsize=(6, 5))
plt.imshow(np.log1p(mat), cmap="Reds")
plt.colorbar(label="log1p(contact count)")
plt.title(region)
plt.show()

chrom = "chr19"
base_start = 465_000
base_end   = 470_000
base = (base_start + base_end) // 2

flank = 200_000

# округляем к 10 kb bins
start = (base - flank) // res * res
end = ((base + flank + res - 1) // res) * res

region = f"{chrom}:{start}-{end}"
view_df = pd.DataFrame({
    "chrom": [chrom],
    "start": [0],
    "end": [int(clr.chromsizes[chrom])],
    "name": [chrom],
})

expected = cooltools.expected_cis(
    clr,
    view_df=view_df,
    smooth=False,
    aggregate_smoothed=False,
    nproc=1,
    chunksize=1_000_000,
)

expected.head()

mat = clr.matrix(balance=True).fetch(region)

exp_chr = expected[
    (expected["region1"] == chrom) &
    (expected["region2"] == chrom)
].copy()


# выбираем колонку expected. Обычно для balanced матриц это balanced.avg
print(exp_chr.columns)

if "balanced.avg" in exp_chr.columns:
    exp_col = "balanced.avg"
elif "balanced.avg.smoothed" in exp_chr.columns:
    exp_col = "balanced.avg.smoothed"
elif "balanced.avg.smoothed.agg" in exp_chr.columns:
    exp_col = "balanced.avg.smoothed.agg"
else:
    exp_col = "count.avg"

exp_by_diag = exp_chr.set_index("dist")[exp_col]

n = mat.shape[0]
diag_ids = np.abs(np.subtract.outer(np.arange(n), np.arange(n)))

exp_mat = exp_by_diag.reindex(diag_ids.ravel()).to_numpy().reshape(n, n)


oe = mat / exp_mat
log_oe = np.log2(oe)

# убрать бесконечности и самую главную диагональ
log_oe[~np.isfinite(log_oe)] = np.nan
np.fill_diagonal(log_oe, np.nan)

log_o = np.log2(mat/np.nanmean(mat))

# убрать бесконечности и самую главную диагональ
log_o[~np.isfinite(log_o)] = np.nan
np.fill_diagonal(log_o, np.nan)
print(np.nanmean(mat))

extent = [
    (start - base) / 1000,
    (end - base) / 1000,
    (end - base) / 1000,
    (start - base) / 1000,
]

plt.figure(figsize=(6, 5))
plt.imshow(
    oe,
    origin="upper",
    extent=extent,
    cmap="coolwarm",
    vmin = 0.8,
    vmax = 1.3
)

plt.colorbar(label="log2 observed / expected")
plt.axvline(0, color="black", lw=0.8, ls="--")
plt.axhline(0, color="black", lw=0.8, ls="--")

# диагональ Hi-C
plt.plot(
    [(start - base) / 1000, (end - base) / 1000],
    [(start - base) / 1000, (end - base) / 1000],
    color="black",
    lw=0.5,
    alpha=0.5,
)

plt.title(f"{region}, base={chrom}:{base_start}-{base_end}")
plt.xlabel("distance from fountain base, kb")
plt.ylabel("distance from fountain base, kb")
plt.show()

size=np.shape(log_oe)[0]

# диагональ Hi-C
plt.plot(
    [10*i for i in range(size//2)],
    [log_oe[size//2+i,size//2-i] for i in range(size//2)],
    color="black"
)
plt.plot(
    [10*i for i in range(size//2-5)],
    [log_oe[size//2+5+i,size//2+5-i] for i in range(size//2-5)],
    color="green",
    lw=1,
    alpha=0.7
)
plt.plot(
    [10*i for i in range(size//2-10)],
    [log_oe[size//2+10+i,size//2+10-i] for i in range(size//2-10)],
    color="red",
    lw=0.5,
    alpha=0.7
)
plt.plot(
    [10*i for i in range(size//2-15)],
    [log_oe[size//2+15+i,size//2+15-i] for i in range(size//2-15)],
    color="blue",
    lw=0.5,
    alpha=0.5
)
data = np.asarray([[10*i for i in range(size//2)],[log_oe[size//2+i,size//2-i] for i in range(size//2)]])
np.savetxt("data_diag.csv", data, delimiter=",")
plt.title(f"{region}, base={chrom}:{base_start}-{base_end}")
plt.xlabel("distance from fountain base, kb")
plt.ylabel("distance from fountain base, kb")
plt.show()

"""**Интерполяция эллипсом**

**Без деления на Expected**
"""

extent = [
    (start - base) / 1000,
    (end - base) / 1000,
    (end - base) / 1000,
    (start - base) / 1000,
]

plt.figure(figsize=(6, 5))
plt.imshow(
    log_o,
    origin="upper",
    extent=extent,
    cmap="coolwarm",
)

plt.colorbar(label="log2 observed / expected")
plt.axvline(0, color="black", lw=0.8, ls="--")
plt.axhline(0, color="black", lw=0.8, ls="--")

size=np.shape(log_oe)[0]
print(log_o)

# диагональ Hi-C
plt.plot(
    [i for i in range(size//2)],
    [log_o[size//2+i,size//2-i] for i in range(size//2)],
    color="black"
)
plt.plot(
    [i for i in range(size//2-5)],
    [log_o[size//2+5+i,size//2+5-i] for i in range(size//2-5)],
    color="green",
    lw=1,
    alpha=0.7
)
plt.plot(
    [i for i in range(size//2-10)],
    [log_o[size//2+10+i,size//2+10-i] for i in range(size//2-10)],
    color="red",
    lw=0.5,
    alpha=0.7
)
plt.plot(
    [i for i in range(size//2-15)],
    [log_o[size//2+15+i,size//2+15-i] for i in range(size//2-15)],
    color="blue",
    lw=0.5,
    alpha=0.5
)

plt.title(f"{region}, base={chrom}:{base_start}-{base_end}")
plt.xlabel("distance from fountain base, kb")
plt.ylabel("distance from fountain base, kb")
plt.show()

"""**Expected**"""

size_exp=np.shape(exp_by_diag)[0]

# диагональ Hi-C
plt.plot(
    [np.log2(i) for i in range(40)],
    [np.log2(exp_by_diag[i]) for i in range(40)],
    color="black"
)
data = np.asarray([[i for i in range(size_exp)],[exp_by_diag[i] for i in range(size_exp)]])
np.savetxt("data.csv", data, delimiter=",")

plt.title(f"{region}, base={chrom}:{base_start}-{base_end}")
plt.xlabel("distance from fountain base, kb")
plt.ylabel("distance from fountain base, kb")
plt.show()

extent = [
    (start - base) / 1000,
    (end - base) / 1000,
    (end - base) / 1000,
    (start - base) / 1000,
]

plt.figure(figsize=(6, 5))
plt.imshow(
    np.log2(exp_mat),
    origin="upper",
    extent=extent,
    cmap="coolwarm",

)

plt.colorbar(label="log2 observed / expected")
plt.axvline(0, color="black", lw=0.8, ls="--")
plt.axhline(0, color="black", lw=0.8, ls="--")

# диагональ Hi-C
plt.plot(
    [(start - base) / 1000, (end - base) / 1000],
    [(start - base) / 1000, (end - base) / 1000],
    color="black",
    lw=0.5,
    alpha=0.5,
)

plt.title(f"{region}, base={chrom}:{base_start}-{base_end}")
plt.xlabel("distance from fountain base, kb")
plt.ylabel("distance from fountain base, kb")
plt.show()

"""# **Массовая обработка для поиска коэффициента корреляции**

> Добавить блок с цитатой


"""

results_df, failed_df, expected_raw = ft.process_fountains_batch(
    cool_path= mcool_path_danio,
    fountains_csv=fountains_path_danio,
    output_csv="fountain_fit_results.csv",
    failed_csv="fountain_fit_failed.csv",
    res=10_000,
    flank=200_000,
    p0_kb=50,
    p_half_window_kb=40,
    fit_window_kb=180,
    diag_exclusion_kb=10,
    z_transform="oe",
    expected_nproc=4,
)

print(results_df.head())
r_fin = results_df["r"].dropna()
plt.figure(figsize=(5, 4))
plt.hist((results_df["r"].dropna())[:500])
plt.xlabel("r = (1 - a/b) / (1 + a/b)")
plt.ylabel("number of fountains")
plt.tight_layout()
plt.show()
print(np.mean((results_df["r"][results_df["r"]>0].dropna())[:500]))
print(np.mean((results_df["r"].dropna())[:500]))
print(np.mean((results_df["r"].dropna())[:100]))
print(np.mean(results_df["q1_r_pearson"]))
plt.plot([i for i in range(len(results_df["r"]))],results_df["r"])
plt.plot([i for i in range(len(r_fin))],results_df["q1_r_pearson"])
plt.show()

"""# Аггрегированный фонтан"""

res = 10000

aggregate_Z, aggregate_info, used_df, failed_df, expected_raw = ft.build_weighted_aggregate_fountain(
    cool_path = mcool_path_madoka,
    fountains_csv=fountains_path_madoka,
    flank=100_000,
    res=5_000,
    weight_col="Fountain Score",
    z_transform="oe",
    expected_nproc=4,
    min_weight=0,
    require_full_window=True,
)

fig, ax, Z_smooth, levels = ft.plot_smoothed_hic_contours(
    aggregate_Z,
    res=res,
    sigma=1.2,
    cmap="coolwarm",
    vmin=0.8,
    vmax=1.3,
    linecolor="blue",
    linewidth=1.5,
    show_image=True,
    levels=[1.04, 1.1, 1.15, 1.2,1.25,1.5,1.6]
)
plt.show()

#Новый фит
print('Новый фит')
fit_agg, fit_cache = ft.fit_aggregate_fountain_old(
    aggregate_Z,
    res=5_000,

    p0_kb=50,
    p_half_window_kb=40,

    peak_penalty=False,
    peak_weight=30.0,
    peak_scale_kb=30.0,
    peak_search_window_kb=70,
    peak_quantile=0.80,
)

print(f"a final:  {fit_agg['a_kb']:.2f} kb")
print(f"b broad:  {fit_agg['b_kb_broad']:.2f} kb")
print(f"b final:  {fit_agg['b_kb']:.2f} kb")
print(f"p final:  {fit_agg['p_kb']:.2f} kb")
print(
    f"r = {fit_agg['r']:.3f} "
    f"± {fit_agg['r_se']:.3f}"
)

#Старый фит
print('Старый фит')
fit_agg, fit_cache = ft.fit_aggregate_fountain_old(
    aggregate_Z,
    res=5_000,

    p0_kb=25,
    p_half_window_kb=50,

    # Широкое окно для предварительного поиска p
    fit_window_kb=70,
    diag_exclusion_kb=10,

    # Затем локальный фит вокруг найденного пика
    two_step_peak_refit=True,
    near_peak_radius_kb=80,

    positive_weight=True,
    positive_weight_strength=10,
    robust=True,

    downweight_major_tail=True,
    major_tail_side="positive",
    major_tail_start_kb=20,
    major_tail_transition_kb=40,
    major_tail_min_scale=0.00001,

    peak_penalty=False,
    peak_weight=100.0,
    peak_scale_kb=5.0,
    peak_search_window_kb=80,
    peak_quantile=0.80,
)

print("p_kb:", fit_agg["p_kb"])
print("Hi-C peak:", fit_agg["hic_peak_x_kb"], fit_agg["hic_peak_y_kb"])
print("Gaussian peak:", fit_agg["gaussian_peak_x_kb"], fit_agg["gaussian_peak_y_kb"])
print("peak_dist_kb:", fit_agg["peak_dist_kb"])
print("peak_penalty:", fit_agg["peak_penalty_value"])
print("peak_is_valid:", fit_agg["peak_is_valid"])

print(f"a final:  {fit_agg['a_kb']:.2f} kb")
print(f"b broad:  {fit_agg['b_kb_broad']:.2f} kb")
print(f"b final:  {fit_agg['b_kb']:.2f} kb")
print(f"p final:  {fit_agg['p_kb']:.2f} kb")
print("RMSE:", fit_agg["rmse"])
print("NRMSE %:", fit_agg["nrmse_percent"])
print("RMSE broad:", fit_agg["rmse_broad"])
print("weighted RMSE:", fit_agg["weighted_rmse"])
print("objective RMS residual:", fit_agg["objective_rms_residual"])
print(
    f"r = {fit_agg['r']:.3f} "
    f"± {fit_agg['r_se']:.3f}")

fig, ax = ft.plot_aggregate_fountain_fit(
    aggregate_Z,
    fit_agg,
    fit_cache,
    image_vmin=0.8,
    image_vmax=1.2,
    output="xenopus.pdf",
    show_hic_contours=True,
    hic_contour_smooth_sigma=1.5,
    norm_hic_levels=(0.5,0.70, 0.85, 0.95),
    norm_gaussian_levels=(0.70, 0.85, 0.95),
    hic_contour_color="black",
    hic_contour_linewidth=3,
    hic_contour_linestyle="--",
    show_fit_contours=True,
    fit_contour_color="fuchsia",
    fit_contour_linewidth=1.8,
    show_fit_contours_mirror=True,
    fit_contour_linestyle="-"
)
plt.show()

"""**Фит агрегированного фонтана аналитической моделью**"""

fit_theory = ft.fit_aggregate_fountain_extrusion_model(
    aggregate_Z=aggregate_Z,
    res=5_000,              # поставь своё разрешение
    orientation="upper",
    fit_max_arm_kb=200,     # можно 200 или 300
    fit_min_arm_kb=0,       # можно 10 или 20, если мешает основание
    lp_bounds=(200, 1200),
    sigma_bounds=(0.016, 0.15),
    gamma_bounds=(1, 10),
    normalize_shape=True,
    positive_weight=True,
    robust=True,
    n_starts=True,
)

fit_theory

fig, axes = ft.plot_extrusion_model_fit(
    aggregate_Z=aggregate_Z,
    fit=fit_theory,
    res=5_000,
)
plt.show()

fig, ax, Z_pred = ft.plot_aggregate_fountain_with_theory_contours(
    aggregate_Z=aggregate_Z,
    fit=fit_theory,
    image_vmin=0.7,
    image_vmax=1.1,
    res=5_000,   # поставь своё разрешение
    orientation="upper",
    cmap="coolwarm",
    contour_color="black",
    show_labels=False,
    output_png="aggregate_fountain_with_theoretical_contours.png",
)
plt.show()

x = aggregate_Z[50:60]
y = np.mean(x,axis=0)

print(np.shape(y))
plt.plot([i for i in range(len(x.T))], x.T)
plt.show()
plt.plot([i for i in range(len(y))], y)
plt.show()
df = pd.DataFrame(y)
df.to_csv('fountaidn.csv', index=False)

fig, ax, models = ft.plot_aggregate_with_gaussian_fit_and_theory(
    aggregate_Z=aggregate_Z,
    gaussian_fit=fit_agg,
    gaussian_fit_cache=fit_cache,
    theory_fit=fit_theory,
    res=5_000,
    orientation="upper",
    image_vmin=0.8,
    image_vmax=1.1,
    theory_levels_frac=( 0.65, 0.8, 0.9),
    gaussian_levels_frac=(0.45, 0.60, 0.75),
    theory_color = "black",
    title = " ",
    output_png="aggregate_fountain_gaussian_and_theory_fit.png",
)

plt.show()

"""**Новый вариант фита**"""

flank_kb = 100
lp_kb = 1750.000
rho_sigma = 0.01025
gamma_c0 = 14.75

# Нужно, чтобы PDE-сетка покрывала область интегрирования.
# Для P(-x1,x2) при xmax = flank/lp максимум l или r примерно до 2*xmax.
xmax = flank_kb / lp_kb
Lmax = 2.2 * xmax

kernel_res = ft.build_numeric_fountain_kernel(
    Lmax=2.2*xmax,
    N=600,
    alpha=0,

    gamma_c0=gamma_c0,  # фоновая gamma
    gamma_c=0,    # без центрального поля
    gamma_b=1.8,

    sigma=0.001,    # почти точечный источник
    sigma2=0.001,

    bottom_mode="gamma0_compatible",
    kernel="Nfin",
)

l_grid = kernel_res["l_grid"]
r_grid = kernel_res["r_grid"]
Nfin = kernel_res["Nfin"]
A_kernel = kernel_res["A_kernel"]


A_kernel = Nfin.copy()

P, LEFT, RIGHT, A_interp = ft.contact_map_from_kernel_array(
    l_grid=l_grid,
    r_grid=r_grid,
    A_kernel=A_kernel,
    xmax=flank_kb / lp_kb,   # потому что flank = 250 kb
    n_map=300,
    rho_mu=0.0,
    rho_sigma=rho_sigma,
    n_int=301,
    normalize=True,
)
P, LEFT, RIGHT, A_interp = ft.contact_map_from_kernel_array(
    l_grid=l_grid,
    r_grid=r_grid,
    A_kernel=A_kernel,

    xmax=xmax,
    n_map=300,

    rho_mu=0.0,
    rho_sigma=rho_sigma,

    n_int=301,
    normalize=True,
)

res_agg = 5_000
# ------------------------------------------------------------
# 2. Накладываем контуры P на агрегированный Hi-C фонтан
# ------------------------------------------------------------

# ------------------------------------------------------------
# 1. Численная contact map P(-x1, x2)
# ------------------------------------------------------------
plot_data = ft.prepare_aggregate_contour_data(
    aggregate_Z=aggregate_Z,
    P=P,
    LEFT=LEFT,
    RIGHT=RIGHT,
    res=res_agg,
    lp_kb=lp_kb,
    orientation="upper",

    hic_contour_smooth_sigma=1.2,
    numeric_contour_smooth_sigma=1.2,

    normalize_contours=True,
    norm_window_kb=150,

    hic_contour_levels=[0.5, 0.7, 0.9],
    numeric_contour_levels= [0.53,0.7,0.92],
    gaussian_contour_levels=[0.5, 0.7, 0.9],

    gaussian_fit=fit_agg,
    gaussian_fit_cache=None,
)


rmse_res = ft.compute_norm_rmse_from_plot_data(
    plot_data,
    orientation="upper",
    center_xy_kb=(40, -40),
    half_window_kb=40,
)

rmse_res["rmse"], rmse_res["n_pixels"]

ft.plot_aggregate_with_numeric_contact_contours(
    plot_data,

    species_name="Oryzyas latipes",
    gamma_c=15.25,
    gamma_b=1.8,

    image_vmin=0.8,
    image_vmax=1.1,

    show_hic_contours=True,
    show_numeric_contours=True,
    show_gaussian_contours=True,
    show_numeric_mirror=True,
    hic_contour_linestyle="--",
    contour_linestyle=":",
    gaussian_linestyle="-",

    linecolor_hic="black",
    contour_color="blue",
    gaussian_color="fuchsia",

    show_legend=True,
    legend_loc="lower right",

    output_png="xenopus.pdf",
)

import numpy as np
import matplotlib.pyplot as plt


# ------------------------------------------------------------
# Parameter grid
# ------------------------------------------------------------

gamma_values = [3, 6, 9, 12, 15]
lp_values = [200, 700, 1200, 1700, 2300]

flank_kb = 250
res_agg = 5_000

rho_sigma_kb_fixed = 17.0

# fixed model params
alpha = 0.0
gamma_c = 0.0
gamma_b = 1.8

sigma = 0.001
sigma2 = 0.001

# numerical params
N = 600
n_map = 300
n_int = 301

# plot params
image_vmin = 0.8
image_vmax = 1.03
image_cmap = "coolwarm"

numeric_contour_levels = [0.5, 0.7, 0.9]
hic_contour_levels = [0.47, 0.7, 0.9]

show_hic_contours = True
show_numeric_contours = True

# ------------------------------------------------------------
# Coordinates for background Hi-C image
# ------------------------------------------------------------

Z = np.asarray(aggregate_Z, dtype=float)
X_grid, Y_grid, coords_kb, extent = ft.make_hic_grid(Z, res_agg)

# ------------------------------------------------------------
# Figure
# ------------------------------------------------------------

fig, axes = plt.subplots(
    nrows=len(lp_values),
    ncols=len(gamma_values),
    figsize=(3.0 * len(gamma_values), 3.0 * len(lp_values)),
    sharex=True,
    sharey=True,
)

for i, lp_kb in enumerate(lp_values):
    for j, gamma_ci in enumerate(gamma_values):

        ax = axes[i, j]

        rho_sigma = rho_sigma_kb_fixed / lp_kb

        xmax = flank_kb / lp_kb
        Lmax = 2.2 * xmax

        # ------------------------------------------------------------
        # Numerical kernel
        # ------------------------------------------------------------

        kernel_res = ft.build_numeric_fountain_kernel(
            Lmax=Lmax,
            N=N,
            alpha=alpha,

            gamma_c0=gamma_ci,
            gamma_c=gamma_c,
            gamma_b=gamma_b,

            sigma=sigma,
            sigma2=sigma2,

            bottom_mode="gamma0_compatible",
            kernel="Nfin",
        )

        P, LEFT, RIGHT, A_interp = ft.contact_map_from_kernel_array(
            l_grid=kernel_res["l_grid"],
            r_grid=kernel_res["r_grid"],
            A_kernel=kernel_res["Nfin"],

            xmax=xmax,
            n_map=n_map,

            rho_mu=0.0,
            rho_sigma=rho_sigma,

            n_int=n_int,
            normalize=True,
        )

        # ------------------------------------------------------------
        # Prepare contours
        # ------------------------------------------------------------

        plot_data = ft.prepare_aggregate_contour_data(
            aggregate_Z=aggregate_Z,
            P=P,
            LEFT=LEFT,
            RIGHT=RIGHT,
            res=res_agg,
            lp_kb=lp_kb,
            orientation="upper",

            hic_contour_smooth_sigma=1.0,
            numeric_contour_smooth_sigma=1.0,

            normalize_contours=True,
            norm_window_kb=150,

            hic_contour_levels=hic_contour_levels,
            numeric_contour_levels=numeric_contour_levels,
            gaussian_contour_levels=[0.5, 0.7, 0.9],

            gaussian_fit=None,
            gaussian_fit_cache=None,
        )

        # ------------------------------------------------------------
        # Background Hi-C map
        # ------------------------------------------------------------

        im = ax.imshow(
            plot_data["Z"],
            origin="upper",
            extent=plot_data["extent"],
            cmap=image_cmap,
            vmin=image_vmin,
            vmax=image_vmax,
            interpolation="nearest",
            aspect="equal",
            zorder=0,
        )

        # ------------------------------------------------------------
        # Hi-C contours
        # ------------------------------------------------------------

        if show_hic_contours and len(plot_data["hic_levels"]) > 0:
            ax.contour(
                plot_data["X_grid"],
                plot_data["Y_grid"],
                plot_data["Z_contour"],
                levels=plot_data["hic_levels"],
                colors="black",
                linewidths=1.0,
                linestyles="solid",
                zorder=10,
            )

        # ------------------------------------------------------------
        # Numerical contours
        # ------------------------------------------------------------

        if show_numeric_contours:
            for item in plot_data["numeric_contour_sets"]:
                if len(item["levels"]) == 0:
                    continue

                ax.contour(
                    item["X"],
                    item["Y"],
                    item["Z"],
                    levels=item["levels"],
                    colors="white",
                    linewidths=1.4,
                    linestyles="--",
                    zorder=20,
                )

                # mirror under main diagonal
                ax.contour(
                    item["Y"].T,
                    item["X"].T,
                    item["Z"].T,
                    levels=item["levels"],
                    colors="white",
                    linewidths=1.4,
                    linestyles="--",
                    zorder=20,
                )

        # ------------------------------------------------------------
        # Guides
        # ------------------------------------------------------------

        ax.axline(
            (0, 0),
            slope=1,
            linestyle="--",
            linewidth=0.8,
            color="gray",
            alpha=0.45,
            zorder=30,
        )

        ax.axline(
            (0, 0),
            slope=-1,
            linestyle=":",
            linewidth=0.8,
            color="gray",
            alpha=0.55,
            zorder=30,
        )

        # ------------------------------------------------------------
        # Titles / labels
        # ------------------------------------------------------------

        if i == 0:
            ax.set_title(rf"$\gamma_c$ = {gamma_ci}", fontsize=12)

        if j == 0:
            ax.set_ylabel(
                rf"$l_p$ = {lp_kb} kb" + "\n" + rf"$\sigma_\rho$ = {rho_sigma:.3f}",
                fontsize=11,
            )

        ax.tick_params(labelsize=8)

# ------------------------------------------------------------
# Shared colorbar
# ------------------------------------------------------------

cbar = fig.colorbar(
    im,
    ax=axes.ravel().tolist(),
    fraction=0.025,
    pad=0.02,
)

cbar.set_label("Hi-C intensity", fontsize=11)

fig.suptitle(
    rf"Fixed loading width: $\sigma_\rho = 50 / l_p$",
    fontsize=14,
    y=0.995,
)

# вместо этого НЕ надо:
# plt.tight_layout(rect=[0, 0, 0.98, 0.97])

# ------------------------------------------------------------
# место под colorbar
# ------------------------------------------------------------
fig.subplots_adjust(
    left=0.08,
    right=0.90,   # оставляем место справа
    bottom=0.06,
    top=0.94,
    wspace=0.05,
    hspace=0.05,
)

# отдельная ось под colorbar
cax = fig.add_axes([0.92, 0.15, 0.02, 0.70])  # [x0, y0, width, height]
cbar = fig.colorbar(im, cax=cax)
cbar.set_label("Hi-C intensity", fontsize=11)

fig.suptitle(
    r"Fixed loading width: $\sigma_\rho = 50 / l_p$",
    fontsize=14,
    y=0.985,
)

plt.savefig(
    "gamma_lp_grid_fixed_rho_sigma_50kb.png",
    dpi=300,
    bbox_inches="tight",
)

plt.show()

# ----------------------------
# начальная точка
# ----------------------------
lp_kb = 500.0
rho_sigma = 0.01
gamma_ci = 5

# ----------------------------
# начальные шаги поиска
# ----------------------------
step_lp = 100.0
step_rho = 0.001
step_gamma = 1.0

# ----------------------------
# границы параметров
# ----------------------------
lp_min, lp_max = 1200.0, 3500.0
rho_min, rho_max = 0.003, 0.06
gamma_min, gamma_max = 0.0, 40.0

# ----------------------------
# peak-aware score params
# ----------------------------
peak_weight = 0          # сила штрафа за промах по пику; можно поднять до 5-10
peak_search_window_kb = 50 # окно, где ищем пик вокруг ожидаемого положения
peak_scale_kb = 20.0       # промах на 20 kb дает штраф порядка peak_weight
peak_quantile = 0.80       # берем верхние 20% сигнала как "верхушку" пика

# ----------------------------
# настройки поиска
# ----------------------------
max_iter = 25
shrink = 0.5
tol_improve = 1e-5

min_step_lp = 10.0
min_step_rho = 0.0001
min_step_gamma = 0.1

history = []
cache = {}

current_rmse = np.inf
current_score = np.inf
current_plot_data = None

for it in range(max_iter):

    candidates = [
        (lp_kb, rho_sigma, gamma_ci, "current"),

        (lp_kb + step_lp, rho_sigma, gamma_ci, "+lp"),
        (lp_kb - step_lp, rho_sigma, gamma_ci, "-lp"),

        (lp_kb, rho_sigma + step_rho, gamma_ci, "+rho"),
        (lp_kb, rho_sigma - step_rho, gamma_ci, "-rho"),

        (lp_kb, rho_sigma, gamma_ci + step_gamma, "+gamma"),
        (lp_kb, rho_sigma, gamma_ci - step_gamma, "-gamma"),
    ]

    evaluated = []

    for lp_try, rho_try, gamma_try, move_name in candidates:

        lp_try = float(np.clip(lp_try, lp_min, lp_max))
        rho_try = float(np.clip(rho_try, rho_min, rho_max))
        gamma_try = float(np.clip(gamma_try, gamma_min, gamma_max))

        key = (
            round(lp_try, 6),
            round(rho_try, 8),
            round(gamma_try, 6),
        )

        if key in cache:
            cached = cache[key]

            rmse = cached["rmse"]
            score = cached["score"]
            peak_dist_kb = cached["peak_dist_kb"]
            peak_penalty = cached["peak_penalty"]
            plot_data_try = cached["plot_data"]

        else:
            xmax = flank_kb / lp_try
            Lmax = 2.2 * xmax

            kernel_res = ft.build_numeric_fountain_kernel(
                Lmax=Lmax,
                N=600,
                alpha=0.0,

                gamma_c0=gamma_try,
                gamma_c=0.0,
                gamma_b=1.8,

                sigma=0.001,
                sigma2=0.001,

                bottom_mode="gamma0_compatible",
                kernel="Nfin",
            )

            A_kernel = kernel_res["Nfin"].copy()

            P, LEFT, RIGHT, A_interp = ft.contact_map_from_kernel_array(
                l_grid=kernel_res["l_grid"],
                r_grid=kernel_res["r_grid"],
                A_kernel=A_kernel,

                xmax=xmax,
                n_map=300,

                rho_mu=0.0,
                rho_sigma=rho_try,

                n_int=301,
                normalize=True,
            )

            plot_data = ft.prepare_aggregate_contour_data(
                aggregate_Z=aggregate_Z,
                P=P,
                LEFT=LEFT,
                RIGHT=RIGHT,
                res=res_agg,
                lp_kb=lp_try,
                orientation="upper",

                hic_contour_smooth_sigma=1.0,
                numeric_contour_smooth_sigma=1.0,

                common_contour_levels=[0.5, 0.7, 0.9],
                normalize_contours=True,
                norm_window_kb=150,

                gaussian_fit=None,
                gaussian_fit_cache=None,
            )

            rmse_res = ft.compute_norm_rmse_from_plot_data(
                plot_data,
                orientation="upper",
                center_xy_kb=(40, -40),
                half_window_kb=40,
            )

            # ------------------------------------------------------------
            # Peak-aware score: сравниваем центр масс верхушки пика
            # ------------------------------------------------------------

            Z_norm = rmse_res["Z_norm"]
            P_norm = rmse_res["P_norm_on_hic"]

            X_grid = plot_data["X_grid"]
            Y_grid = plot_data["Y_grid"]

            cx, cy = (40, -40)

            peak_mask = (
                (np.abs(X_grid - cx) <= peak_search_window_kb) &
                (np.abs(Y_grid - cy) <= peak_search_window_kb) &
                np.isfinite(Z_norm) &
                np.isfinite(P_norm)
            )

            if peak_mask.sum() < 5:
                rmse = np.inf
                peak_dist_kb = np.inf
                peak_penalty = np.inf
                score = np.inf

            else:
                rmse = float(rmse_res["rmse"])

                Z_local = Z_norm[peak_mask]
                P_local = P_norm[peak_mask]
                X_local = X_grid[peak_mask]
                Y_local = Y_grid[peak_mask]

                z_thr = np.nanquantile(Z_local, peak_quantile)
                p_thr = np.nanquantile(P_local, peak_quantile)

                z_top = Z_local >= z_thr
                p_top = P_local >= p_thr

                if z_top.sum() < 3 or p_top.sum() < 3:
                    peak_dist_kb = np.inf
                    peak_penalty = np.inf
                    score = np.inf

                else:
                    wz = Z_local[z_top] - z_thr
                    wp = P_local[p_top] - p_thr

                    if np.sum(wz) <= 0:
                        wz = np.ones_like(wz)

                    if np.sum(wp) <= 0:
                        wp = np.ones_like(wp)

                    z_peak_x = np.average(X_local[z_top], weights=wz)
                    z_peak_y = np.average(Y_local[z_top], weights=wz)

                    p_peak_x = np.average(X_local[p_top], weights=wp)
                    p_peak_y = np.average(Y_local[p_top], weights=wp)

                    peak_dist_kb = np.sqrt(
                        (p_peak_x - z_peak_x) ** 2 +
                        (p_peak_y - z_peak_y) ** 2
                    )

                    peak_penalty = peak_weight * (peak_dist_kb / peak_scale_kb) ** 2
                    score = rmse + peak_penalty

            plot_data_try = plot_data

            cache[key] = {
                "rmse": rmse,
                "score": score,
                "peak_dist_kb": peak_dist_kb,
                "peak_penalty": peak_penalty,
                "plot_data": plot_data_try,
            }

        row = {
            "iter": it,
            "move": move_name,
            "lp_kb": lp_try,
            "rho_sigma": rho_try,
            "rho_sigma_kb": rho_try * lp_try,
            "gamma_c0": gamma_try,
            "rmse": rmse,
            "score": score,
            "peak_dist_kb": peak_dist_kb,
            "peak_penalty": peak_penalty,
            "step_lp": step_lp,
            "step_rho": step_rho,
            "step_gamma": step_gamma,
        }

        history.append(row)
        evaluated.append({
            **row,
            "plot_data": plot_data_try,
        })

        print(
            f"iter={it:02d} {move_name:>8s} | "
            f"lp={lp_try:.1f}, "
            f"rho={rho_try:.5f} ({rho_try * lp_try:.1f} kb), "
            f"gamma={gamma_try:.2f}, "
            f"rmse={rmse:.5f}, "
            f"peak_dist={peak_dist_kb:.1f} kb, "
            f"peak_penalty={peak_penalty:.5f}, "
            f"score={score:.5f}"
        )

    best_row = min(evaluated, key=lambda x: x["score"])

    if best_row["score"] < current_score - tol_improve:
        lp_kb = best_row["lp_kb"]
        rho_sigma = best_row["rho_sigma"]
        gamma_ci = best_row["gamma_c0"]

        current_rmse = best_row["rmse"]
        current_score = best_row["score"]
        current_plot_data = best_row["plot_data"]

        print(
            "\nACCEPT:",
            f"move={best_row['move']},",
            f"lp={lp_kb:.1f},",
            f"rho={rho_sigma:.5f},",
            f"gamma={gamma_ci:.2f},",
            f"rmse={current_rmse:.5f},",
            f"peak_dist={best_row['peak_dist_kb']:.1f} kb,",
            f"peak_penalty={best_row['peak_penalty']:.5f},",
            f"score={current_score:.5f}",
            "\n"
        )

    else:
        step_lp *= shrink
        step_rho *= shrink
        step_gamma *= shrink

        print(
            "\nNO IMPROVEMENT -> shrink steps:",
            f"step_lp={step_lp:.3g},",
            f"step_rho={step_rho:.3g},",
            f"step_gamma={step_gamma:.3g}",
            "\n"
        )

    if (
        step_lp <= min_step_lp
        and step_rho <= min_step_rho
        and step_gamma <= min_step_gamma
    ):
        print("STOP: steps are small enough.")
        break


history_df = pd.DataFrame(history)

print("BEST:")
print(
    f"lp_kb = {lp_kb:.3f}\n"
    f"rho_sigma = {rho_sigma:.6f}\n"
    f"rho_sigma_kb = {rho_sigma * lp_kb:.3f}\n"
    f"gamma_c0 = {gamma_ci:.3f}\n"
    f"rmse = {current_rmse:.6f}\n"
    f"score = {current_score:.6f}"
)

gamma_grid = np.arange(15, 9, -2)

profile_rows = []

for gamma_value in gamma_grid:
    fit_prof = ft.fit_numeric_fountain_coordinate_descent(
        aggregate_Z=aggregate_Z,
        flank_kb=flank_kb,
        res_agg=res_agg,

        lp_kb=500.0,
        rho_sigma=0.01,
        gamma_c0=gamma_value,
        min_step_lp=100.0,
        min_step_rho=0.001,
        min_step_gamma=0.1,
        step_lp=300.0,
        step_rho=0.002,
        step_gamma=1.0,

        fixed_params={
            "gamma_c0": gamma_value,
        },

        verbose=True,
        verbose_level=1,
    )

    row = {
        **fit_prof["best_params"],
        "best_rmse": fit_prof["best_rmse"],
        "best_score": fit_prof["best_score"],
        "fixed_gamma_c0": gamma_value,
    }

    profile_rows.append(row)

profile_df = pd.DataFrame(profile_rows)

#критический rmse для расчета погрешности

smooth_floor = ft.compute_smoothing_rmse_floor(
    aggregate_Z=aggregate_Z,
    fit_cache=fit_cache,
    fit=fit_agg,
    near_peak_radius_kb=70,
    diag_exclusion_kb=10,
    smoothing_sigma_bins=1.0,
    normalize=False,
)

smooth_floor

thresholds = ft.profile_rmse_threshold_from_smoothing(
    rmse_min=fit_agg["rmse"],
    smoothing_rmse=smooth_floor["smoothing_rmse"],
)

thresholds

"""**Фит распределения с когезинами**"""

fit_prob, Z_prob_pred, shape_prob, fit_mask_prob, opt_prob = ft.fit_aggregate_fountain_probability_model(
    aggregate_Z=aggregate_Z,
    res=res,
    orientation="upper",
    fit_min_arm_kb=0,
    fit_max_arm_kb=400,
    D1_nonnegative=True,
    max_nfev=500,
)

fit_prob

fit_prob

def plot_probability_model_fit(
    aggregate_Z,
    Z_pred,
    res=5000,
    image_vmin=0.5,
    image_vmax=1.6,
    residual_vmax=None,
):
    Z = np.asarray(aggregate_Z, dtype=float)
    pred = np.asarray(Z_pred, dtype=float)
    residual = Z - pred

    n = Z.shape[0]
    bin_kb = res / 1000.0
    coords_kb = (np.arange(n) - (n - 1) / 2.0) * bin_kb
    extent = [coords_kb.min(), coords_kb.max(), coords_kb.max(), coords_kb.min()]

    if residual_vmax is None:
        vals = residual[np.isfinite(residual)]
        residual_vmax = np.nanquantile(np.abs(vals), 0.99)

    fig, axes = plt.subplots(1, 3, figsize=(14, 4.4))

    im0 = axes[0].imshow(
        Z,
        origin="upper",
        extent=extent,
        cmap="coolwarm",
        vmin=image_vmin,
        vmax=image_vmax,
        interpolation="nearest",
    )
    axes[0].set_title("Data")
    plt.colorbar(im0, ax=axes[0], fraction=0.046)

    im1 = axes[1].imshow(
        pred,
        origin="upper",
        extent=extent,
        cmap="coolwarm",
        vmin=image_vmin,
        vmax=image_vmax,
        interpolation="nearest",
    )
    axes[1].set_title("Analytical model")
    plt.colorbar(im1, ax=axes[1], fraction=0.046)

    im2 = axes[2].imshow(
        residual,
        origin="upper",
        extent=extent,
        cmap="coolwarm",
        vmin=-residual_vmax,
        vmax=residual_vmax,
        interpolation="nearest",
    )
    axes[2].set_title("Residual")
    plt.colorbar(im2, ax=axes[2], fraction=0.046)

    for ax in axes:
        ax.axline((0, 0), slope=1, linestyle="--", linewidth=1, color="black", alpha=0.45)
        ax.axline((0, 0), slope=-1, linestyle=":", linewidth=1, color="black", alpha=0.45)
        ax.set_xlabel("Distance from fountain base, kb")
        ax.set_ylabel("Distance from fountain base, kb")

    plt.tight_layout()
    return fig, axes

fig, axes = plot_probability_model_fit(
    aggregate_Z=aggregate_Z,
    Z_pred=Z_prob_pred,
    res=res,
    image_vmin=0.5,
    image_vmax=1.6,
)

plt.show()

def plot_probability_model_contours_on_data(
    aggregate_Z,
    Z_pred,
    res=5000,
    image_vmin=0.5,
    image_vmax=1.6,
    contour_fractions=(0.35, 0.50, 0.70, 0.85),
):
    Z = np.asarray(aggregate_Z, dtype=float)
    pred = np.asarray(Z_pred, dtype=float)

    n = Z.shape[0]
    bin_kb = res / 1000.0
    coords_kb = (np.arange(n) - (n - 1) / 2.0) * bin_kb
    X, Y = np.meshgrid(coords_kb, coords_kb)

    extent = [coords_kb.min(), coords_kb.max(), coords_kb.max(), coords_kb.min()]

    fig, ax = plt.subplots(figsize=(6.0, 5.4))

    im = ax.imshow(
        Z,
        origin="upper",
        extent=extent,
        cmap="coolwarm",
        vmin=image_vmin,
        vmax=image_vmax,
        interpolation="nearest",
    )

    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

    vals = pred[np.isfinite(pred)]
    C = np.nanmin(vals)
    A = np.nanmax(vals) - C
    levels = C + A * np.array(contour_fractions)

    ax.contour(
        X,
        Y,
        pred,
        levels=levels,
        colors="black",
        linewidths=1.5,
    )

    ax.axline((0, 0), slope=1, linestyle="--", linewidth=1, color="gray", alpha=0.7)
    ax.axline((0, 0), slope=-1, linestyle=":", linewidth=1, color="gray", alpha=0.7)

    ax.set_xlabel("Distance from fountain base, kb")
    ax.set_ylabel("Distance from fountain base, kb")

    plt.tight_layout()
    return fig, ax

fig, ax = plot_probability_model_contours_on_data(
    aggregate_Z=aggregate_Z,
    Z_pred=Z_prob_pred,
    res=res,
    image_vmin=0.5,
    image_vmax=1.3,
)

plt.show()

"""**Рисование 2д профилей**"""

profile_df, gaussian_df, meta = ft.make_ellipse_axis_profile_data(
    aggregate_Z=aggregate_Z,
    fit=fit_agg,
    res=5_000,
    profile_range_kb=300,
    bin_width_kb=10,
    strip_halfwidth_kb=15,
    upper_triangle=True,
    diag_exclusion_kb=10,
)
experimental_profile_points = ft.save_experimental_profile_points(
    profile_df=profile_df,
    meta=meta,
    output_csv="experimental_axis_profile_points.csv",
    experiment_name="WT_5.3hpf",
    aggregate_name="all_fountains",
    include_empty_bins=False,
)

fig, ax = ft.plot_ellipse_axis_profiles_barplot(
    profile_df,
    gaussian_df,
    meta=meta,
    show_sem=True,
    bar_alpha=0.45,
    bar_from_background=False,
)
plt.show()
profile_df.to_csv(
    "profile_df.csv",
    index=False,
)

"""# Фонтаны + промоторы"""

promoters_df = ft.load_baranasic_promoters(
    baranasik_path_danio,
    sheet_name=0,
    chrom_col="Chromosome",
    start_col="Start",
    end_col="End",
)
promoter_hits_df, promoter_summary_df = ft.find_promoters_near_fountains(
    fountains_df=results_df,
    promoters_df=promoters_df,
    window_bp=200_000,
    fountain_id_col="Fountain index",
    base_col="base_bp",
)
fountain_with_promoters_df = results_df.merge(
    promoter_summary_df,
    on=["Fountain index", "chrom", "base_bp"],
    how="left",
)

print(fountain_with_promoters_df)

"""# Работа с файлом из алгоритма PADRE


"""

reg = ft.load_dome_chromhmm_bed(padre_path_danio)

reg.head()
reg["state"].value_counts()

enhancers = ft.select_chromhmm_features(
    reg,
    feature_type="enhancer",
    mode="strict",   # основной вариант: только 5_EnhA1
)

promoters = ft.select_chromhmm_features(
    reg,
    feature_type="promoter",
    mode="strict",   # основной вариант: 1_TssA1 + 2_TssA2
)

print("Enhancers:", len(enhancers))
print(enhancers["state"].value_counts())

print("Promoters:", len(promoters))
print(promoters["state"].value_counts())

fountains = ft.prepare_fountains_for_annotation(results_df)

fountains = ft.harmonize_chrom_style(fountains, reg)

enhancer_summary, enhancer_hits_at_base = ft.annotate_fountains_with_nearby_features(
    fountains_df=fountains,
    features_df=enhancers,
    feature_name="enhancer",
    max_distance_bp=10_000,  # можно 0, 10_000, 20_000
    fountain_id_col="Fountain index",
    base_col="base_bp",
)

fountains_enh_annotated = fountains.merge(
    enhancer_summary,
    on=["Fountain index", "chrom", "base_bp"],
    how="left",
)

fountains_near_enhancer = fountains_enh_annotated[
    fountains_enh_annotated["n_enhancers_overlapping_fountain_bin"] > 0
].copy()

fountains_near_enhancer_10kb = fountains_enh_annotated[
    fountains_enh_annotated["nearest_enhancer_distance_bp"] <= 10_000
].copy()

promoter_hits_200kb, promoter_summary_200kb = ft.find_features_in_window_around_fountains(
    fountains_df=fountains_near_enhancer,
    features_df=promoters,
    feature_name="promoter",
    window_bp=200_000,
    fountain_id_col="Fountain index",
    base_col="base_bp",
)

fountains_near_enhancer_with_promoters = fountains_near_enhancer.merge(
    promoter_summary_200kb,
    on=["Fountain index", "chrom", "base_bp"],
    how="left",
)

fountains_near_enhancer_with_promoters.to_csv(
    "fountains_near_Dome_EnhA1_with_promoters_200kb.csv",
    index=False,
)

promoter_hits_200kb.to_csv(
    "promoter_hits_around_fountains_near_Dome_EnhA1_200kb.csv",
    index=False,
)

enhancer_hits_at_base.to_csv(
    "enhancer_hits_at_fountain_base_bins.csv",
    index=False,
)

"""# Распределение расстояний до промоторов"""

print(promoter_hits_200kb.shape)
print(promoter_hits_200kb.columns)

promoter_hits_200kb[
    [
        "Fountain index",
        "fountain_chrom",
        "fountain_base_bp",
        "promoter_chrom",
        "promoter_start",
        "promoter_end",
        "promoter_center",
        "promoter_state",
        "distance_to_promoter_interval_bp",
        "signed_distance_to_promoter_center_bp",
        "abs_distance_to_promoter_center_bp",
    ]
].head()

promoter_hits_200kb.to_csv("promoters.csv")

fig, ax = ft.plot_signed_promoter_distances(
    promoter_hits_200kb,
    bin_width_kb=10,
    window_kb=200,
    title="Promoters within ±200 kb of enhancer-associated fountains",
    output_png="signed_promoter_distances_200kb.png",
)

plt.show()

fig, ax = ft.plot_signed_promoter_distances(
    promoter_hits_200kb,
    bin_width_kb=10,
    window_kb=200,
    title="Promoters within ±200 kb of enhancer-associated fountains",
    output_png="signed_promoter_distances_200kb.png",
)

plt.show()

fig, ax = ft.plot_abs_promoter_distances(
    promoter_hits_200kb,
    bin_width_kb=10,
    window_kb=200,
    title="Absolute distances to promoters within ±200 kb",
    output_png="absolute_promoter_distances_200kb.png",
)

plt.show()



"""# Визуализация EP-контактов на аггрегированном фонтане"""

from matplotlib.patches import Rectangle
from matplotlib.collections import LineCollection, PatchCollection

enhancer_fountain_hits = ft.find_enhancers_near_fountains(
    fountains_df=fountains,
    enhancers_df=enhancers,
    max_enhancer_distance_bp=300_000,
    fountain_id_col="Fountain index",
    base_col="base_bp",
)

print(enhancer_fountain_hits.shape)
enhancer_fountain_hits.head()

ep_contacts = ft.build_enhancer_promoter_contacts_around_fountains(
    enhancer_fountain_hits=enhancer_fountain_hits,
    promoters_df=promoters,
    promoter_window_bp=200_000,
    fountain_id_col="Fountain index",
)

print(ep_uniq)
ep_contacts.head()

ep_uniq=ep_contacts[["enhancer_feature_id", "enhancer_distance_to_base_bp","Fountain Score","Fountain index"]]

ep_uniq=ep_uniq.drop_duplicates(subset=["enhancer_feature_id"])
plt.hist(ep_uniq["enhancer_distance_to_base_bp"], bins=30, color='skyblue', edgecolor='black', alpha=0.7)
plt.xlabel("Distance to base, kb")
plt.xlim((0,80000))
plt.show()
ep_uniq2 = (
    ep_contacts[
        [
            "Fountain index",
            "enhancer_feature_id",
            "enhancer_distance_to_base_bp",
            "Fountain Score",
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["Fountain index", "enhancer_distance_to_base_bp"]
    )
    .drop_duplicates("Fountain index", keep="first")
    .reset_index(drop=True)
)
plt.scatter(ep_uniq2["enhancer_distance_to_base_bp"],ep_uniq2["Fountain Score"])
plt.show()

enhancer_fountain_hits.to_csv(
    "enhancers_within_10kb_of_fountain_base.csv",
    index=False,
)

ep_contacts.to_csv(
    "candidate_enhancer_promoter_contacts_around_fountains_200kb.csv",
    index=False,
)

fig, ax = ft.plot_ep_contacts_on_aggregate_fountain(
    ep_contacts=ep_contacts,
    aggregate_Z=aggregate_Z,
    res=5_000,
    plot_window_kb=50,
    background_vmin=0.5,
    background_vmax=1.6,
    contact_alpha=0.035,
    output_png="aggregate_fountain_with_candidate_EP_contacts.png",
)

plt.show()

fig, ax, H_ep, ep_edges, ep_centers = ft.plot_ep_contact_density_on_aggregate_fountain(
    ep_contacts=ep_contacts,
    aggregate_Z=aggregate_Z,
    res=5_000,
    density_cmap='YlGn',
    plot_window_kb=200,
    bin_width_kb=5,
    density_alpha=0.25,
    output_png="aggregate_fountain_with_EP_contact_density.png",
)

plt.show()



"""# Визуализация ориентированного аггрегированного фонтана

> Добавить блок с цитатой


"""

bar_raw = pd.read_csv(baranasik_path_danio,sep=';')
bar_raw.columns.tolist()

baranasic_promoters = ft.load_baranasic_promoters_oriented(
    baranasik_path_danio,
    sheet_name=0,
    sep=';'
)

baranasic_promoters.head()

oriented_padre_promoters = ft.match_padre_promoters_to_baranasic(
    padre_promoters=promoters,
    baranasic_promoters=baranasic_promoters,
    max_match_distance_bp=0,      # 0 = требуем пересечение интервалов
    keep_all_matches=False,       # один лучший Baranasic-промотор на один PADRE-промотор
    drop_ambiguous_strand=False,  # не выбрасываем divergent cases, но флаг сохраняется
)

oriented_padre_promoters["gene_strand"].value_counts(dropna=False)

oriented_padre_promoters[
    [
        "chrom",
        "start",
        "end",
        "state",
        "gene_strand",
        "baranasic_tss",
        "baranasic_gene_name",
        "distance_to_padre_interval_bp",
        "padre_baranasic_overlap_bp",
        "n_baranasic_matches_for_padre",
        "n_baranasic_strands_for_padre",
    ]
].head()

oriented_ep_table = ft.build_enhancer_fountain_nearest_oriented_promoter_table(
    enhancer_fountain_hits=enhancer_fountain_hits,
    oriented_padre_promoters=oriented_padre_promoters,
    max_ep_distance_bp=70_000,
    fountain_id_col="Fountain index",
    promoter_anchor_col="baranasic_tss",
)

oriented_ep_table.to_csv(
    "enhancer_fountain_nearest_oriented_promoter_70kb.csv",
    index=False,
)

oriented_ep_table

oriented_ep_one_per_fountain = ft.select_one_oriented_contact_per_fountain(
    oriented_ep_table,
    fountain_id_col="Fountain index",
    prefer="nearest_ep",
)

oriented_ep_one_per_fountain.to_csv(
    "one_oriented_EP_contact_per_fountain.csv",
    index=False,
)

oriented_aggregate_Z, oriented_info, oriented_used_df, oriented_failed_df, expected_raw = (
    ft.build_oriented_aggregate_fountain(
        cool_path=mcool_path_danio,
        fountains=fountains,
        oriented_ep_table=oriented_ep_one_per_fountain,
        flank=300_000,
        res=5_000,
        weight_col="Fountain Score",
        z_transform="oe",
        expected_nproc=4,
        min_weight=0,
        require_full_window=True,
        base_shift_bp=-6000,
        fountain_id_col="Fountain index",
        minus_reflect=True,
        contact_prefer="nearest_ep",
    )
)

fig, ax = ft.plot_oriented_aggregate_fountain(
    oriented_aggregate_Z,
    res=5_000,
    vmin=0.5,
    vmax=1.6,
    title=(
        f"Oriented aggregate fountain\n"
        f"n={oriented_info['n_used']}, "
        f"+={oriented_info['n_plus']}, "
        f"-={oriented_info['n_minus']}"
    ),
    output_png="oriented_aggregate_fountain.png",
)

plt.show()

"""# Визуализация фонтана на энхансерах"""

ENHANCER_DISTANCE_BP = 50_000
enh_col = f"n_enhancers_within_{ENHANCER_DISTANCE_BP}_bp"
enhancer_summary, enhancer_hits_near_base = ft.annotate_fountains_with_nearby_features(
    fountains_df=fountains,
    features_df=enhancers,
    feature_name="enhancer",
    max_distance_bp=ENHANCER_DISTANCE_BP,
    fountain_id_col="Fountain index",
    base_col="base_bp",
)

fountains_annot = fountains.merge(
    enhancer_summary[
        [
            "Fountain index",
            "chrom",
            "base_bp",
            enh_col,
            "n_enhancers_overlapping_fountain_bin",
            "nearest_enhancer_distance_bp",
            "nearest_enhancer_state",
            "nearest_enhancer_start",
            "nearest_enhancer_end",
            "nearest_enhancer_score",
        ]
    ],
    on=["Fountain index", "chrom", "base_bp"],
    how="left",
)
print(fountains_annot)

fountains_annot["has_enhancer_near_base_50kb"] = (
    fountains_annot[enh_col].fillna(0).astype(int) > 0
)

fountains_with_enhancer = fountains_annot[
    fountains_annot["has_enhancer_near_base_50kb"]
].copy()

fountains_without_enhancer = fountains_annot[
    ~fountains_annot["has_enhancer_near_base_50kb"]
].copy()

print("All fountains:", len(fountains_annot))
print("With enhancer at base:", len(fountains_with_enhancer))
print("Without enhancer at base:", len(fountains_without_enhancer))

fountains_annot.to_csv(
    "fountains_annotated_by_enhancer_at_base.csv",
    index=False,
)

fountains_with_enhancer.to_csv(
    "fountains_with_enhancer_at_base.csv",
    index=False,
    sep=";",
)

fountains_without_enhancer.to_csv(
    "fountains_without_enhancer_at_base.csv",
    index=False,
    sep=";",
)

enhancer_hits_at_base.to_csv(
    "enhancer_hits_at_fountain_base.csv",
    index=False,
)

res = 5_000
flank = 300_000
weight_col = "Fountain Score"
z_transform = "oe"
expected_nproc = 4
agg_with_enhancer_Z, info_with_enhancer, used_with_enhancer, failed_with_enhancer, expected_raw_with = (
    ft.build_weighted_aggregate_fountain(
        cool_path=mcool_path_danio,
        fountains_csv=str("fountains_with_enhancer_at_base.csv"),
        flank=flank,
        res=res,
        weight_col=weight_col,
        z_transform=z_transform,
        expected_nproc=expected_nproc,
        min_weight=0,
        require_full_window=True,
    )
)

used_with_enhancer.to_csv(
     "aggregate_with_enhancer_used.csv",
    index=False,
)

failed_with_enhancer.to_csv(
    "aggregate_with_enhancer_failed.csv",
    index=False,
)

info_with_enhancer

fountains_annot.to_csv(
    "fountains_annotated_by_enhancer_at_base.csv",
    index=False,
)

fountains_with_enhancer.to_csv(
     "fountains_with_enhancer_at_base.csv",
    index=False,
    sep=";",
)

fountains_without_enhancer.to_csv(
    "fountains_without_enhancer_at_base.csv",
    index=False,
    sep=";",
)

enhancer_hits_at_base.to_csv(
    "enhancer_hits_at_fountain_base.csv",
    index=False,
)

agg_without_enhancer_Z, info_without_enhancer, used_without_enhancer, failed_without_enhancer, expected_raw_without = (
    ft.build_weighted_aggregate_fountain(
        cool_path=mcool_path_danio,
        fountains_csv=str("fountains_without_enhancer_at_base.csv"),
        flank=flank,
        res=res,
        weight_col=weight_col,
        z_transform=z_transform,
        expected_nproc=expected_nproc,
        min_weight=0,
        require_full_window=True,
    )
)

used_without_enhancer.to_csv(
    "aggregate_without_enhancer_used.csv",
    index=False,
)

failed_without_enhancer.to_csv(
    "aggregate_without_enhancer_failed.csv",
    index=False,
)

info_without_enhancer

diff_Z = agg_with_enhancer_Z / agg_without_enhancer_Z

np.save("agg_with_enhancer_Z.npy", agg_with_enhancer_Z)
np.save("agg_without_enhancer_Z.npy", agg_without_enhancer_Z)
np.save("diff_with_minus_without_Z.npy", diff_Z)

from matplotlib.collections import LineCollection
from matplotlib.colors import Normalize


def make_enhancer_density_segments(
    enhancer_hits,
    plot_window_kb,
    bin_width_kb=5,
    fountain_id_col="Fountain index",
    enhancer_id_col="enhancer_feature_id",
    start_col="enhancer_rel_start_kb",
    end_col="enhancer_rel_end_kb",
    center_col="enhancer_rel_center_kb",
    use_intervals=True,
):
    """
    Делает плотность энхансеров вдоль главной диагонали.

    Возвращает:
        segments : список отрезков [(x0,y0), (x1,y1)] на линии x=y
        density  : число энхансеров в каждом bin
        edges    : границы bin-ов
        centers  : центры bin-ов

    Если use_intervals=True:
        энхансер засчитывается во все бины, которые пересекает его интервал.

    Если use_intervals=False:
        энхансер засчитывается только по center.
    """

    df = enhancer_hits.copy()

    # ВАЖНО: если на вход пришел ep_contacts, там enhancer может повторяться
    # много раз из-за разных промоторов.
    dedup_cols = [
        c for c in [fountain_id_col, enhancer_id_col, start_col, end_col, center_col]
        if c in df.columns
    ]

    df = df[dedup_cols].drop_duplicates().copy()

    edges = np.arange(
        -plot_window_kb,
        plot_window_kb + bin_width_kb,
        bin_width_kb,
    )
    centers = 0.5 * (edges[:-1] + edges[1:])

    density = np.zeros(len(centers), dtype=float)

    if use_intervals and start_col in df.columns and end_col in df.columns:
        for _, row in df.iterrows():
            s = float(row[start_col])
            e = float(row[end_col])

            lo = max(min(s, e), -plot_window_kb)
            hi = min(max(s, e), plot_window_kb)

            if hi < -plot_window_kb or lo > plot_window_kb:
                continue

            i0 = np.searchsorted(edges, lo, side="right") - 1
            i1 = np.searchsorted(edges, hi, side="left")

            i0 = max(i0, 0)
            i1 = min(i1, len(centers) - 1)

            if i1 >= i0:
                density[i0:i1 + 1] += 1

    else:
        x = df[center_col].to_numpy(dtype=float)
        x = x[np.isfinite(x)]
        x = x[(x >= -plot_window_kb) & (x <= plot_window_kb)]
        density, _ = np.histogram(x, bins=edges)

    segments = [
        [(edges[i], edges[i]), (edges[i + 1], edges[i + 1])]
        for i in range(len(centers))
    ]

    return segments, density, edges, centers

def plot_enhancer_vs_no_enhancer_separate(
    agg_with,
    agg_without,
    enhancer_hits_with=None,
    enhancer_hits_without=None,
    res=5_000,
    signal_vmin=0.5,
    signal_vmax=1.6,
    title_with=None,
    title_without=None,
    output_png_with=None,
    output_png_without=None,
    cmap="coolwarm",
    dpi=600,
    enhancer_density_bin_kb=5,
    enhancer_density_cmap="Greys",
    enhancer_density_lw=8,
    enhancer_density_alpha=0.95,
    enhancer_density_use_intervals=True,
    show_enhancer_density_colorbar=True,
):
    n = agg_with.shape[0]
    bin_kb = res / 1000
    coords_kb = ft.make_centered_coords(n, bin_kb)

    extent = [
        coords_kb.min(),
        coords_kb.max(),
        coords_kb.max(),
        coords_kb.min(),
    ]

    plot_window_kb = max(abs(coords_kb.min()), abs(coords_kb.max()))

    # Общая нормировка плотности для двух картинок,
    # чтобы цвета были сравнимы.
    density_vmax = None

    density_precomputed = {}

    for label, hits in [
        ("with", enhancer_hits_with),
        ("without", enhancer_hits_without),
    ]:
        if hits is None:
            continue

        segments, density, edges, centers = make_enhancer_density_segments(
            hits,
            plot_window_kb=plot_window_kb,
            bin_width_kb=enhancer_density_bin_kb,
            use_intervals=enhancer_density_use_intervals,
        )

        density_precomputed[label] = {
            "segments": segments,
            "density": density,
            "edges": edges,
            "centers": centers,
        }

        local_max = np.nanmax(density) if len(density) else 0

        if density_vmax is None:
            density_vmax = local_max
        else:
            density_vmax = max(density_vmax, local_max)

    if density_vmax is None or density_vmax <= 0:
        density_vmax = 1.0

    density_norm = Normalize(vmin=0, vmax=density_vmax)

    def plot_one(Z, title=None, output_png=None, density_data=None):
        fig, ax = plt.subplots(figsize=(8, 8))

        im = ax.imshow(
            Z,
            origin="upper",
            extent=extent,
            aspect="equal",
            interpolation="nearest",
            cmap=cmap,
            vmin=signal_vmin,
            vmax=signal_vmax,
        )

        ax.axline(
            (0, 0),
            slope=1,
            linestyle="--",
            linewidth=1,
            color="black",
            alpha=0.5,
        )

        ax.axline(
            (0, 0),
            slope=-1,
            linestyle=":",
            linewidth=1,
            color="black",
            alpha=0.5,
        )

        # ----------------------------
        # Enhancer density on main diagonal
        # ----------------------------
        if density_data is not None:
            segments = density_data["segments"]
            density = density_data["density"]

            # Чтобы нулевые бины не закрашивали диагональ
            nonzero = density > 0

            segments_nonzero = [
                seg for seg, keep in zip(segments, nonzero) if keep
            ]
            density_nonzero = density[nonzero]

            if len(segments_nonzero) > 0:
                lc = LineCollection(
                    segments_nonzero,
                    cmap=enhancer_density_cmap,
                    norm=density_norm,
                    linewidths=enhancer_density_lw,
                    alpha=enhancer_density_alpha,
                    zorder=10,
                    capstyle="butt",
                )
                lc.set_array(density_nonzero)
                ax.add_collection(lc)

                if show_enhancer_density_colorbar:
                    cbar_enh = plt.colorbar(
                        lc,
                        ax=ax,
                        fraction=0.046,
                        pad=0.10,
                    )
                    cbar_enh.set_label("Enhancer density", fontsize=14)
                    cbar_enh.ax.tick_params(labelsize=13)

        cbar = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        cbar.ax.tick_params(labelsize=15)

        ax.tick_params(axis="both", which="major", labelsize=16)
        ax.tick_params(axis="both", which="minor", labelsize=16)

        # ax.set_xlabel("Distance from fountain base, kb", fontsize=18)
        # ax.set_ylabel("Distance from fountain base, kb", fontsize=18)

        # if title is not None:
        #     ax.set_title(title, fontsize=18)

        plt.tight_layout()

        if output_png is not None:
            fig.savefig(output_png, bbox_inches="tight", dpi=dpi)

        return fig, ax

    fig_with, ax_with = plot_one(
        agg_with,
        title=title_with or "Fountains with enhancer",
        output_png=output_png_with,
        density_data=density_precomputed.get("with"),
    )

    fig_without, ax_without = plot_one(
        agg_without,
        title=title_without or "Fountains without enhancer",
        output_png=output_png_without,
        density_data=density_precomputed.get("without"),
    )

    return (fig_with, ax_with), (fig_without, ax_without), density_precomputed

enhancer_fountain_hits_50 = ft.find_enhancers_near_fountains(
    fountains_df=fountains,
    enhancers_df=enhancers,
    max_enhancer_distance_bp=50_000,
    fountain_id_col="Fountain index",
    base_col="base_bp",
)

enhancer_fountain_hits_300 = ft.find_enhancers_near_fountains(
    fountains_df=fountains,
    enhancers_df=enhancers,
    max_enhancer_distance_bp=300_000,
    fountain_id_col="Fountain index",
    base_col="base_bp",
)

merged = enhancer_fountain_hits_300.merge(enhancer_fountain_hits_50, how="outer", indicator=True)
enhancer_fountain_hits_300_50 = merged[merged["_merge"] == "left_only"].drop(columns="_merge")

(fig_with, ax_with), (fig_without, ax_without), enh_density = (
    plot_enhancer_vs_no_enhancer_separate(
        agg_with=agg_with_enhancer_Z,
        agg_without=agg_without_enhancer_Z,
        enhancer_hits_with=enhancer_fountain_hits_50,
        enhancer_hits_without=enhancer_fountain_hits_300_50,
        res=5_000,
        output_png_with="aggregate_with_enhancer_density.pdf",
        output_png_without="aggregate_without_enhancer.pdf",
        show_enhancer_density_colorbar=False
    )
)



"""#Построение фонтана, выровненного относительно энхансера"""

enhancer_fountain_hits = ft.find_enhancers_near_fountains(
    fountains_df=fountains,
    enhancers_df=enhancers,
    max_enhancer_distance_bp=50_000,
    fountain_id_col="Fountain index",
    base_col="base_bp",
)

print(enhancer_fountain_hits.shape)
enhancer_fountain_hits.head()

nearest_enhancer_per_fountain = ft.select_nearest_enhancer_per_fountain(
    enhancer_fountain_hits,
    fountain_id_col="Fountain index",
)

nearest_enhancer_per_fountain.to_csv(
    "nearest_enhancer_per_fountain.csv",
    index=False,
)

enh_aligned_Z, enh_aligned_info, enh_aligned_used, enh_aligned_failed, enh_expected_raw = (
    ft.build_enhancer_aligned_aggregate_fountain(
        cool_path=mcool_path_danio,
        nearest_enhancer_per_fountain=nearest_enhancer_per_fountain,
        flank=300_000,
        res=5_000,
        weight_col="Fountain Score",
        z_transform="oe",
        expected_nproc=4,
        min_weight=0,
        require_full_window=True,
    )
)

enh_aligned_info

np.save("enhancer_aligned_aggregate_Z.npy", enh_aligned_Z)

enh_aligned_used.to_csv(
    "enhancer_aligned_aggregate_used.csv",
    index=False,
)

enh_aligned_failed.to_csv(
    "enhancer_aligned_aggregate_failed.csv",
    index=False,
)

fig, ax = ft.plot_enhancer_aligned_aggregate(
    enh_aligned_Z,
    res=5_000,
    vmin=0.5,
    vmax=1.6,
    title=f"Enhancer-aligned aggregate, n={enh_aligned_info['n_used']}",
    output_png="enhancer_aligned_aggregate.png",
)

plt.show()

fig, ax = ft.plot_aggregate_fountain(
    aggregate_Z,
    fit_agg,
    fit_cache,
    vmin=0.5,
    vmax=1.6
)

plt.show()



"""#Рисую одиночные фонтаны и рядом с ними энхансеры"""

def select_top_fountain_enhancer_hits(
    enhancer_hits,
    n_top=1,
    score_col="Fountain Score",
    fountain_id_col="Fountain index",
    max_distance_bp=None,
):
    """
    Из уже готовой таблицы enhancer_hits выбирает все enhancer hits
    для top-n фонтанов по Fountain Score.

    enhancer_hits: long-table, где одна строка = fountain-enhancer pair.
    """

    hits = enhancer_hits.copy()

    if max_distance_bp is not None:
        hits = hits[
            hits["enhancer_distance_to_base_bp"] <= max_distance_bp
        ].copy()

    # Одна строка на фонтан, чтобы выбрать top-n фонтанов по скору
    fountain_cols = [
        c for c in [
            fountain_id_col,
            "chrom",
            "base_bp",
            score_col,
        ]
        if c in hits.columns
    ]

    top_fountains = (
        hits[fountain_cols]
        .drop_duplicates(subset=[fountain_id_col])
        .sort_values(score_col, ascending=False)
        .head(n_top)
        .copy()
        .reset_index(drop=True)
    )

    top_fountains["top_rank"] = np.arange(1, len(top_fountains) + 1)

    # Оставляем все энхансеры для выбранных фонтанов
    top_hits = hits.merge(
        top_fountains[[fountain_id_col, "top_rank"]],
        on=fountain_id_col,
        how="inner",
    )

    sort_cols = [
        "top_rank",
        "enhancer_distance_to_base_bp",
    ]

    if "enhancer_feature_id" in top_hits.columns:
        sort_cols.append("enhancer_feature_id")

    top_hits = (
        top_hits
        .sort_values(sort_cols)
        .reset_index(drop=True)
    )

    return top_hits, top_fountains

enhancer_fountain_hits = ft.find_enhancers_near_fountains(
    fountains_df=fountains,
    enhancers_df=enhancers,
    max_enhancer_distance_bp=50_000,
    fountain_id_col="Fountain index",
    base_col="base_bp",
)
top_enhancer_hits, top_fountains = select_top_fountain_enhancer_hits(
    enhancer_hits=enhancer_fountain_hits,
    n_top=8,
    score_col="Fountain Score",
    fountain_id_col="Fountain index",
    max_distance_bp=200_000,   # можно None, если enhancer_hits уже ограничен нужным окном
)

from scipy.stats import linregress
from scipy.stats import spearmanr, pearsonr

enh_50kb_summary = (
    enhancer_fountain_hits
    .query("enhancer_distance_to_base_bp <= 50000")
    .groupby("Fountain index", as_index=False)
    .agg(
        **{
            "Fountain Score": ("Fountain Score", "first"),
            "n_enhancers_50kb": ("enhancer_feature_id", "nunique"),
        }
    )
    .sort_values("Fountain Score", ascending=False)
    .reset_index(drop=True)
)

score_by_enh_n = (
    enh_50kb_summary
    .groupby("n_enhancers_50kb", as_index=False)
    .agg(
        mean_score=("Fountain Score", "mean"),
        std_score=("Fountain Score", "std"),
        n_fountains=("Fountain Score", "count"),
    )
)
print(score_by_enh_n)

df_corr = enh_50kb_summary[
    ["n_enhancers_50kb", "Fountain Score"]
].dropna().copy()

x = df_corr["n_enhancers_50kb"]
y = df_corr["Fountain Score"]

rho_spearman, p_spearman = spearmanr(x, y)
r_pearson, p_pearson = pearsonr(x, y)

print(f"Spearman rho = {rho_spearman:.3f}, p = {p_spearman:.3g}")
print(f"Pearson r = {r_pearson:.3f}, p = {p_pearson:.3g}")
print(f"n fountains = {len(df_corr)}")

# фильтруем только надежные группы
plot_df_filt = score_by_enh_n[score_by_enh_n["n_fountains"] >= 3].copy()

x = plot_df_filt["n_enhancers_50kb"].to_numpy(dtype=float)
y = plot_df_filt["mean_score"].to_numpy(dtype=float)
n = plot_df_filt["n_fountains"].to_numpy(dtype=int)

# линейный тренд по средним значениям
lin = linregress(x, y)

x_line = np.linspace(x.min(), x.max(), 200)
y_line = lin.intercept + lin.slope * x_line


plot_df = score_by_enh_n.sort_values("n_enhancers_50kb").copy()

plt.figure(figsize=(5, 5))

plt.errorbar(
    plot_df["n_enhancers_50kb"],
    plot_df["mean_score"],
    yerr=plot_df["std_score"],
    fmt="o",
    capsize=5,
    capthick=1.5,
    elinewidth=1.5,
    markersize=10,
    linewidth=2,
    color='red',
    ecolor = 'black'
)

# линейный тренд
plt.plot(
    x_line,
    y_line,
    linewidth=2,
    alpha=0.9,
    label=(
        f"Linear trend: slope={lin.slope:.3f},\n"
        f"R²={lin.rvalue**2:.2f}, p={lin.pvalue:.3g}"
    ),
    linestyle='dashed', color='black',
    zorder=2,
)



plt.xlabel("Number of enhancers within 50 kb", fontsize=13)
plt.ylabel("Mean fountain score", fontsize=13)
plt.legend(frameon=False, fontsize=10)

plt.xticks(plot_df["n_enhancers_50kb"])
plt.xlim((0,9.5))

plt.tight_layout()
plt.show()

from matplotlib.collections import LineCollection
def plot_top_fountain_enhancers_on_diagonal(
    enhancer_hits,
    cool_path,
    res=10_000,
    flank_bp=200_000,
    n_top=None,
    score_col="Fountain Score",
    fountain_id_col="Fountain index",
    base_col="base_bp",
    chrom_col="chrom",
    z_transform="oe",   # "oe" or "log_oe"
    require_full_window=True,
    base_shift_bp=0,
    output_png=None,
    dpi=300,
    cmap="coolwarm",
    vmin=0.5,
    vmax=1.6,
    enhancer_color="black",
    enhancer_lw=20,
):
    """
    Для top-фонтанов рисует:
      фонтан (Hi-C O/E или log2 O/E)
      + главную диагональ
      + побочную диагональ
      + все энхансеры как отрезки на главной диагонали.

    enhancer_hits:
        long-table, где одна строка = fountain-enhancer pair.
        Ожидаются колонки:
            Fountain index, chrom, base_bp, Fountain Score,
            enhancer_rel_start_kb, enhancer_rel_end_kb
        и желательно top_rank.
    """

    hits = enhancer_hits.copy()

    # --------------------------------------------------
    # 1. Определяем top_rank, если его еще нет
    # --------------------------------------------------
    if "top_rank" not in hits.columns:
        top_fountains = (
            hits[[fountain_id_col, chrom_col, base_col, score_col]]
            .drop_duplicates(subset=[fountain_id_col])
            .sort_values(score_col, ascending=False)
            .copy()
            .reset_index(drop=True)
        )

        if n_top is not None:
            top_fountains = top_fountains.head(n_top).copy()

        top_fountains["top_rank"] = np.arange(1, len(top_fountains) + 1)

        hits = hits.merge(
            top_fountains[[fountain_id_col, "top_rank"]],
            on=fountain_id_col,
            how="inner",
        )
    else:
        if n_top is not None:
            hits = hits[hits["top_rank"] <= n_top].copy()

    ranks = sorted(hits["top_rank"].dropna().unique())
    if len(ranks) == 0:
        raise ValueError("После фильтрации не осталось ни одного фонтана.")

    # --------------------------------------------------
    # 2. Открываем cooler
    # --------------------------------------------------
    clr = cooler.Cooler(f"{cool_path}::resolutions/{res}")
    matrix_selector = clr.matrix(balance=True)

    # если в enhancer_hits стиль хромосом не совпадает с mcool
    if hasattr(ft, "harmonize_fountain_chroms_to_cooler"):
        hits = ft.harmonize_fountain_chroms_to_cooler(
            hits,
            clr,
            chrom_col=chrom_col,
        )

    # --------------------------------------------------
    # 3. Считаем expected заранее только для нужных хромосом
    # --------------------------------------------------
    chroms = sorted(hits[chrom_col].astype(str).unique())

    view_df = pd.DataFrame({
        "chrom": chroms,
        "start": [0] * len(chroms),
        "end": [int(clr.chromsizes[c]) for c in chroms],
        "name": chroms,
    })

    expected_raw = cooltools.expected_cis(
        clr,
        view_df=view_df,
        smooth=False,
        aggregate_smoothed=False,
        nproc=1,
        chunksize=1_000_000,
    )

    if "balanced.avg" in expected_raw.columns:
        exp_col = "balanced.avg"
    elif "balanced.avg.smoothed" in expected_raw.columns:
        exp_col = "balanced.avg.smoothed"
    elif "balanced.avg.smoothed.agg" in expected_raw.columns:
        exp_col = "balanced.avg.smoothed.agg"
    else:
        exp_col = "count.avg"

    expected_by_chrom = {}
    for chrom in chroms:
        sub = expected_raw[
            (expected_raw["region1"] == chrom)
            & (expected_raw["region2"] == chrom)
        ].copy()

        expected_by_chrom[chrom] = sub.set_index("dist")[exp_col]

    def make_exp_mat(chrom, n):
        diag_ids = np.abs(np.subtract.outer(np.arange(n), np.arange(n)))
        exp_series = expected_by_chrom[chrom]
        exp_mat = exp_series.reindex(diag_ids.ravel()).to_numpy().reshape(n, n)
        return exp_mat

    # --------------------------------------------------
    # 4. Вспомогательная функция: достать один фонтан
    # --------------------------------------------------
    def extract_one_fountain(chrom, base_bp):
        base_bp = int(base_bp) + int(base_shift_bp)

        chrom_len = int(clr.chromsizes[chrom])

        # центрируем по bin, содержащему базу
        center_bin_start = (base_bp // res) * res
        start = center_bin_start - flank_bp
        end = center_bin_start + flank_bp + res

        if start < 0 or end > chrom_len:
            if require_full_window:
                raise ValueError(
                    f"Window выходит за границу хромосомы: "
                    f"{chrom}:{start}-{end}, chrom_len={chrom_len}"
                )
            start = max(0, start)
            end = min(chrom_len, end)

        region = f"{chrom}:{start}-{end}"
        mat = matrix_selector.fetch(region)
        mat = np.asarray(mat, dtype=float)

        if mat.shape[0] != mat.shape[1]:
            raise ValueError(f"Non-square matrix for {region}: {mat.shape}")

        exp_mat = make_exp_mat(chrom, mat.shape[0])

        with np.errstate(divide="ignore", invalid="ignore"):
            oe = mat / exp_mat

        oe[~np.isfinite(oe)] = np.nan
        np.fill_diagonal(oe, np.nan)

        if z_transform == "oe":
            Z = oe
        elif z_transform == "log_oe":
            with np.errstate(divide="ignore", invalid="ignore"):
                Z = np.log2(oe)
            Z[~np.isfinite(Z)] = np.nan
            np.fill_diagonal(Z, np.nan)
        else:
            raise ValueError("z_transform должен быть 'oe' или 'log_oe'")

        return Z

    # --------------------------------------------------
    # 5. Рисуем
    # --------------------------------------------------
    n_panels = len(ranks)
    fig, axes = plt.subplots(
        n_panels,
        1,
        figsize=(7, max(4.8 * n_panels, 5)),
        squeeze=False,
    )
    axes = axes[:, 0]

    for ax, rank in zip(axes, ranks):
        sub = hits[hits["top_rank"] == rank].copy()

        if len(sub) == 0:
            ax.set_title(f"Rank {rank}: no data")
            continue

        first = sub.iloc[0]
        chrom = str(first[chrom_col])
        base_bp = int(first[base_col])
        fountain_id = first[fountain_id_col]
        score = float(first[score_col])

        # ---- фонтан ----
        Z = extract_one_fountain(chrom, base_bp)

        n = Z.shape[0]
        coords_kb = ft.make_centered_coords(n, res / 1000)

        extent = [
            coords_kb.min(),
            coords_kb.max(),
            coords_kb.max(),
            coords_kb.min(),
        ]

        im = ax.imshow(
            Z,
            origin="upper",
            extent=extent,
            aspect="equal",
            interpolation="nearest",
            cmap=cmap,
            vmin=vmin,
            vmax=vmax,
        )

        # ---- диагонали ----
        ax.axline((0, 0), slope=1, linestyle="--", linewidth=1, color="black", alpha=0.6)
        ax.axline((0, 0), slope=-1, linestyle=":", linewidth=1, color="black", alpha=0.6)

        # ---- энхансеры на главной диагонали ----
        valid = sub[np.isfinite(sub["enhancer_rel_start_kb"])].copy()

        segments = []
        for _, row in valid.iterrows():
            s = float(row["enhancer_rel_start_kb"])
            e = float(row["enhancer_rel_end_kb"])

            s_clip = max(s, coords_kb.min())
            e_clip = min(e, coords_kb.max())

            if e_clip < coords_kb.min() or s_clip > coords_kb.max():
                continue

            segments.append([(s_clip, s_clip), (e_clip, e_clip)])

        if segments:
            lc = LineCollection(
                segments,
                linewidths=enhancer_lw,
                colors=enhancer_color,
                capstyle="butt",
                zorder=10,
            )
            ax.add_collection(lc)

        ax.set_xlim(coords_kb.min(), coords_kb.max())
        ax.set_ylim(coords_kb.max(), coords_kb.min())

        ax.set_xlabel("Distance from fountain base, kb", fontsize = 13)
        ax.set_ylabel("Distance from fountain base, kb", fontsize = 13)

        ax.set_title(
            f"rank {rank}, fountain {fountain_id}, \n"
            f" score={score:.2f}, enhancers={len(valid)}",
            fontsize=13,
        )

        cbar = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        if z_transform == "oe":
            cbar.set_label("Observed / expected", fontsize = 13)
        else:
            cbar.set_label("log2(O/E)")

    plt.tight_layout()

    if output_png is not None:
        fig.savefig(output_png, bbox_inches="tight", dpi=dpi)

    return fig, axes

for rank in sorted(top_enhancer_hits["top_rank"].dropna().unique()):
    sub = top_enhancer_hits[top_enhancer_hits["top_rank"] == rank].copy()

    fig, axes = plot_top_fountain_enhancers_on_diagonal(
        enhancer_hits=sub,
        cool_path=mcool_path_danio,
        res=10_000,
        flank_bp=200_000,
        n_top=None,
        z_transform="oe",
        output_png=f"fountain_rank_{int(rank):03d}.png",
    )



"""#Какие гены обогащены рядом с промоторами?"""

import pandas as pd
import numpy as np
import re

def parse_gtf_attrs(attr):
    d = {}
    for m in re.finditer(r'(\S+) "([^"]+)"', str(attr)):
        d[m.group(1)] = m.group(2)
    return d


def load_genes_from_gtf(gtf_path, feature="gene"):
    cols = [
        "chrom", "source", "feature", "start", "end",
        "score", "strand", "frame", "attributes"
    ]

    gtf = pd.read_csv(
        gtf_path,
        sep="\t",
        comment="#",
        names=cols,
        low_memory=False,
    )

    genes = gtf[gtf["feature"] == feature].copy()

    attrs = genes["attributes"].apply(parse_gtf_attrs)

    genes["gene_id"] = attrs.apply(lambda x: x.get("gene_id", np.nan))
    genes["gene_name"] = attrs.apply(lambda x: x.get("gene_name", x.get("gene_id", np.nan)))
    genes["gene_biotype"] = attrs.apply(
        lambda x: x.get("gene_biotype", x.get("gene_type", np.nan))
    )

    genes["start"] = genes["start"].astype(int) - 1  # GTF 1-based -> BED-like 0-based
    genes["end"] = genes["end"].astype(int)

    genes["tss"] = np.where(
        genes["strand"] == "+",
        genes["start"],
        genes["end"],
    ).astype(int)

    return genes[
        [
            "chrom",
            "start",
            "end",
            "strand",
            "tss",
            "gene_id",
            "gene_name",
            "gene_biotype",
        ]
    ].drop_duplicates()

genes = load_genes_from_gtf(genes_path_danio)
genes.head()

nc_to_chr = {
    f"NC_007{111 + i}.7": f"chr{i}"
    for i in range(1, 26)
}

genes["chrom_original"] = genes["chrom"]
genes["chrom"] = genes["chrom"].map(nc_to_chr).fillna(genes["chrom"])

genes[["chrom_original", "chrom"]].drop_duplicates().head(30)

def keep_genes_with_tss_in_padre_promoters(
    genes_df,
    padre_promoters,
    tss_col="tss",
):
    """
    Оставляет только гены, у которых TSS попадает внутрь PADRE promoter interval.
    """

    genes = genes_df.copy()
    prom = padre_promoters.copy()

    prom = ft.harmonize_chrom_style(prom, genes)

    rows = []

    prom_by_chrom = {
        chrom: g.sort_values("start").reset_index(drop=True)
        for chrom, g in prom.groupby("chrom", sort=False)
    }

    for _, gene in genes.iterrows():
        chrom = str(gene["chrom"])
        tss = int(gene[tss_col])

        if chrom not in prom_by_chrom:
            continue

        p = prom_by_chrom[chrom]

        hits = p[
            (p["start"].astype(int) <= tss)
            & (p["end"].astype(int) > tss)
        ]

        if len(hits) == 0:
            continue

        # если TSS попал в несколько PADRE-promoter intervals,
        # оставим первый, но можно хранить и все
        h = hits.iloc[0]

        row = gene.to_dict()
        row["padre_promoter_feature_id"] = h.get("feature_id", np.nan)
        row["padre_promoter_state"] = h.get("state", np.nan)
        row["padre_promoter_start"] = int(h["start"])
        row["padre_promoter_end"] = int(h["end"])
        row["n_padre_promoters_overlapping_tss"] = len(hits)

        rows.append(row)

    return pd.DataFrame(rows)

padre_promoters = ft.select_chromhmm_features(
    reg,
    feature_type="promoter",
    mode="strict",
)

padre_enhancers = ft.select_chromhmm_features(
    reg,
    feature_type="enhancer",
    mode="strict",
)

genes_padre_tss = keep_genes_with_tss_in_padre_promoters(
    genes_df=genes,
    padre_promoters=padre_promoters,
)

print("All genes:", len(genes))
print("Genes with PADRE promoter TSS:", len(genes_padre_tss))

padre_chroms = set(padre_promoters["chrom"].astype(str).unique())

genes_main = genes[
    genes["chrom"].astype(str).isin(padre_chroms)
].copy()

print("genes total:", len(genes))
print("genes on PADRE chromosomes:", len(genes_main))
print("PADRE chroms:", sorted(padre_chroms)[:30])
print("genes chroms:", sorted(genes_main["chrom"].astype(str).unique())[:30])

def find_genes_near_fountains(
    fountains_df,
    genes_df,
    window_bp=100_000,
    fountain_id_col="Fountain index",
    base_col="base_bp",
    score_col="Fountain Score",
):
    fountains = ft.prepare_fountains_for_annotation(fountains_df).copy()
    genes = genes_df.copy()

    if hasattr(ft, "harmonize_chrom_style"):
        genes = ft.harmonize_chrom_style(genes, fountains)

    genes_by_chrom = {
        chrom: g.sort_values("tss").reset_index(drop=True)
        for chrom, g in genes.groupby("chrom", sort=False)
    }

    rows = []

    for _, f in fountains.iterrows():
        chrom = str(f["chrom"])
        base = int(f[base_col])

        if chrom not in genes_by_chrom:
            continue

        g = genes_by_chrom[chrom]

        hits = g[
            (g["tss"] >= base - window_bp)
            & (g["tss"] <= base + window_bp)
        ].copy()

        for _, gene in hits.iterrows():
            rows.append({
                fountain_id_col: f[fountain_id_col],
                "chrom": chrom,
                "base_bp": base,
                score_col: f.get(score_col, np.nan),

                "gene_id": gene["gene_id"],
                "gene_name": gene["gene_name"],
                "gene_biotype": gene["gene_biotype"],
                "gene_strand": gene["strand"],
                "gene_tss": int(gene["tss"]),
                "gene_start": int(gene["start"]),
                "gene_end": int(gene["end"]),

                "signed_distance_tss_to_base_bp": int(gene["tss"]) - base,
                "abs_distance_tss_to_base_bp": abs(int(gene["tss"]) - base),
                "window_bp": window_bp,
            })

    return pd.DataFrame(rows)

enhancer_fountain_hits = ft.find_enhancers_near_fountains(
    fountains_df=fountains,
    enhancers_df=enhancers,
    max_enhancer_distance_bp=300_000,
    fountain_id_col="Fountain index",
    base_col="base_bp",
)

fountain_ids_with_enh_50kb = (
    enhancer_fountain_hits
    .query("enhancer_distance_to_base_bp <= 50000")
    ["Fountain index"]
    .unique()
)

fountains_with_enh_50kb = fountains[
    fountains["Fountain index"].isin(fountain_ids_with_enh_50kb)
].copy()

print(len(fountains_with_enh_50kb))

gene_hits_100kb = find_genes_near_fountains(
    fountains_df=fountains_with_enh_50kb ,
    genes_df=genes,
    window_bp=100_000,
)

gene_hits_100kb.to_csv(
    "genes_near_fountains_100kb_PADRE_TSS_only.csv",
    index=False,
)

fountain_gene_summary = (
    gene_hits_100kb
    .sort_values(["Fountain index", "abs_distance_tss_to_base_bp"])
    .groupby("Fountain index", as_index=False)
    .agg(
        chrom=("chrom", "first"),
        base_bp=("base_bp", "first"),
        **{
            "Fountain Score": ("Fountain Score", "first"),
            "n_genes_100kb": ("gene_id", "nunique"),
            "nearest_gene": ("gene_name", "first"),
            "nearest_gene_distance_bp": ("signed_distance_tss_to_base_bp", "first"),
            "all_genes_100kb": ("gene_name", lambda x: ";".join(map(str, pd.unique(x)))),
        }
    )
    .sort_values("Fountain Score", ascending=False)
    .reset_index(drop=True)
)

fountain_gene_summary.to_csv("fountain_gene_summary_100kb.csv", index=False)
fountain_gene_summary.head()

gene_biotype_counts = (
    gene_hits_100kb
    .drop_duplicates("gene_id")
    ["gene_biotype"]
    .value_counts()
    .reset_index()
)

gene_biotype_counts.columns = ["gene_biotype", "n_genes"]
gene_biotype_counts

top_nearest_genes = (
    gene_hits_100kb
    .sort_values(["Fountain Score", "abs_distance_tss_to_base_bp"], ascending=[False, True])
    .drop_duplicates("Fountain index")
    [
        [
            "Fountain index",
            "Fountain Score",
            "chrom",
            "base_bp",
            "gene_name",
            "gene_biotype",
            "signed_distance_tss_to_base_bp",
        ]
    ]
)

top_nearest_genes.head(30)

query_genes = sorted(
    gene_hits_100kb["gene_name"].dropna().unique()
)

background_genes = sorted(
    find_genes_near_fountains(
        fountains_df=fountains,
        genes_df=genes,
        window_bp=100_000,
    )["gene_name"].dropna().unique()
)

len(query_genes), len(background_genes)

top_fountains = (
    fountains
    .sort_values("Fountain Score", ascending=False)
    .head(200)
    .copy()
)

top_gene_hits = find_genes_near_fountains(
    fountains_df=top_fountains,
    genes_df=genes,
    window_bp=100_000,
)

query_genes = sorted(top_gene_hits["gene_name"].dropna().unique())

from gprofiler import GProfiler

gp = GProfiler(return_dataframe=True)

enrichment = gp.profile(
    organism="drerio",
    query=query_genes,
    background=background_genes,
    sources=["GO:BP", "GO:MF", "GO:CC", "REAC"],
)

enrichment.to_csv("fountain_nearby_genes_gprofiler_enrichment.csv", index=False)
enrichment.head(20)

enrichment

