# -*- coding: utf-8 -*-
"""Xenopus tropicalis_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XFCis7E0Cls21cTfKAgYaUStgroKr946

#Загрузка библиотек и файлов
"""

pip install cooltools

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os
from scipy.optimize import least_squares
from tqdm.auto import tqdm
import re
from scipy.optimize import least_squares
from scipy.special import erf

import cooltools
data_dir = './drive/MyDrive/fountains/data/'
import cooler

from google.colab import drive
drive.mount('/content/drive')

import sys
LIB_DIR = "./drive/MyDrive/fountains/"

if LIB_DIR not in sys.path:
    sys.path.append(LIB_DIR)

import fountain_tools_clean as ft

import importlib
importlib.reload(ft)

mcool_path_danio = "drive/MyDrive/fountains/data/GSE195609_Wild-Type_5.3.1000.mcool"
mcool_path_xenopus = "drive/MyDrive/fountains/data/stage11.xenTro10.mapq_30.1000.mcool"
mcool_path_madoka = "drive/MyDrive/fountains/data/HiC_st10.oryLat2.mapq_30.1000.mcool"
fountains_path_danio = "drive/MyDrive/fountains/fountains.csv"
fountains_path_xenopus ="drive/MyDrive/fountains/fountains_xenopus.csv"
fountains_path_madoka =  "drive/MyDrive/fountains/fountains_madoka.csv"
padre_path_danio = "drive/MyDrive/fountains/PADRE_DOME.csv"
baranasik_path_danio = "drive/MyDrive/fountains/baranasik.csv"
genes_path_danio = "drive/MyDrive/fountains/data/genomic.gtf"
genes_path_xenopus = "drive/MyDrive/fountains/data/xenopus_genes.gtf.gz"
reg_path_xenopus = "drive/MyDrive/fountains/XENTR_stage105_regulatory_annotation_TssA1_EnhA1_v2.tsv"

"""#Аннотация энхансеров и промоторов"""

!wget -c https://mbdata.science.ru.nl/track_data/Xentr10_0/bw/H3K4me1stage105pk.bigNarrowPeak
!wget -c https://mbdata.science.ru.nl/track_data/Xentr10_0/bw/H3K9acstage105pk.bigNarrowPeak
!wget -c https://mbdata.science.ru.nl/track_data/Xentr10_0/bw/p300stage105pk.bigNarrowPeak
!wget -c https://mbdata.science.ru.nl/track_data/Xentr10_0/bw/H3K4me3stage105pk.bigNarrowPeak
!wget -c https://mbdata.science.ru.nl/track_data/Xentr10_0/bw/RNAPIIstage105pk.bigNarrowPeak

!wget -c http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigBedToBed
!chmod +x bigBedToBed

!./bigBedToBed H3K4me1stage105pk.bigNarrowPeak H3K4me1stage105pk.bed
!./bigBedToBed H3K9acstage105pk.bigNarrowPeak H3K9acstage105pk.bed
!./bigBedToBed p300stage105pk.bigNarrowPeak p300stage105pk.bed
!./bigBedToBed H3K4me3stage105pk.bigNarrowPeak H3K4me3stage105pk.bed
!./bigBedToBed RNAPIIstage105pk.bigNarrowPeak RNAPIIstage105pk.bed

genes_gtf = "genes.gtf.gz"

h3k4me1_bed = "H3K4me1stage105pk.bed"
h3k4me3_bed = "H3K4me3stage105pk.bed"
h3k9ac_bed  = "H3K9acstage105pk.bed"
p300_bed    = "p300stage105pk.bed"
rnapii_bed  = "RNAPIIstage105pk.bed"

out_prefix = "XENTR_stage105"

def read_narrowpeak(path):
    """
    Reads narrowPeak / BED-like peak file.

    Expected columns:
    chrom, start, end, name, score, strand, signalValue, pValue, qValue, peak
    But works if there are at least 3 columns.
    """
    df = pd.read_csv(
        path,
        sep="\t",
        header=None,
        comment="#",
    )

    base_cols = [
        "chrom", "start", "end", "name", "score", "strand",
        "signalValue", "pValue", "qValue", "peak"
    ]

    n = df.shape[1]
    df.columns = base_cols[:n] + [f"extra_{i}" for i in range(n - len(base_cols))]

    df["chrom"] = df["chrom"].astype(str)
    df["start"] = df["start"].astype(int)
    df["end"] = df["end"].astype(int)

    if "score" not in df.columns:
        df["score"] = 1000

    df["score"] = pd.to_numeric(df["score"], errors="coerce").fillna(0).astype(float)
    df["score"] = df["score"].clip(0, 1000).astype(int)

    if "strand" not in df.columns:
        df["strand"] = "."

    return df


def parse_gtf_attributes(attr):
    """
    Parses GTF attributes:
    gene_id "..."; transcript_id "..."; gene_name "...";
    """
    out = {}
    for item in str(attr).strip().split(";"):
        item = item.strip()
        if not item:
            continue

        if " " in item:
            key, value = item.split(" ", 1)
            out[key] = value.strip().strip('"')

    return out


def read_gtf_transcript_tss(gtf_path, protein_coding_only=False):
    """
    Extract transcript-level TSS from GTF.

    GTF is 1-based inclusive.
    BED output is 0-based half-open.
    """
    cols = [
        "chrom", "source", "feature", "start", "end",
        "score", "strand", "frame", "attributes"
    ]

    gtf = pd.read_csv(
        gtf_path,
        sep="\t",
        comment="#",
        header=None,
        names=cols,
        compression="infer",
    )

    tx = gtf[gtf["feature"] == "transcript"].copy()

    tx["start"] = tx["start"].astype(int)
    tx["end"] = tx["end"].astype(int)
    tx["chrom"] = tx["chrom"].astype(str)

    attrs = tx["attributes"].apply(parse_gtf_attributes)

    tx["gene_id"] = attrs.apply(lambda d: d.get("gene_id"))
    tx["transcript_id"] = attrs.apply(lambda d: d.get("transcript_id"))
    tx["gene_name"] = attrs.apply(lambda d: d.get("gene_name"))
    tx["gene_biotype"] = attrs.apply(lambda d: d.get("gene_biotype") or d.get("gene_type"))
    tx["transcript_biotype"] = attrs.apply(lambda d: d.get("transcript_biotype") or d.get("transcript_type"))

    if protein_coding_only:
        tx = tx[
            (tx["gene_biotype"] == "protein_coding") |
            (tx["transcript_biotype"] == "protein_coding")
        ].copy()

    # TSS as 0-based coordinate
    tx["tss0"] = np.where(
        tx["strand"] == "+",
        tx["start"] - 1,
        tx["end"] - 1,
    ).astype(int)

    tss = tx[
        [
            "chrom", "tss0", "strand",
            "gene_id", "transcript_id", "gene_name",
            "gene_biotype", "transcript_biotype"
        ]
    ].copy()

    # убираем точные дубликаты transcript/TSS
    tss = tss.drop_duplicates(
        subset=["chrom", "tss0", "strand", "gene_id", "transcript_id"]
    ).reset_index(drop=True)

    return tss


def make_tss_windows(tss_df, window_bp=1000):
    """
    Makes TSS-centered promoter windows.
    """
    prom = tss_df.copy()
    prom["start"] = (prom["tss0"] - window_bp).clip(lower=0).astype(int)
    prom["end"] = (prom["tss0"] + window_bp + 1).astype(int)
    return prom


def overlap_any(a, b, a_start="start", a_end="end", b_start="start", b_end="end"):
    """
    Fast boolean overlap test:
    for each interval in a, checks if it overlaps at least one interval in b.

    Intervals are 0-based half-open: [start, end).
    """
    out = np.zeros(len(a), dtype=bool)

    if len(a) == 0 or len(b) == 0:
        return out

    a = a.reset_index(drop=True)
    b = b.reset_index(drop=True)

    for chrom, idx_a in a.groupby("chrom").groups.items():
        if chrom not in set(b["chrom"]):
            continue

        aa = a.loc[idx_a]
        bb = b[b["chrom"] == chrom].copy()

        bs = np.sort(bb[b_start].to_numpy(dtype=int))
        be = np.sort(bb[b_end].to_numpy(dtype=int))

        a_s = aa[a_start].to_numpy(dtype=int)
        a_e = aa[a_end].to_numpy(dtype=int)

        # B.start < A.end
        n_started = np.searchsorted(bs, a_e, side="left")

        # B.end <= A.start
        n_ended = np.searchsorted(be, a_s, side="right")

        has = (n_started - n_ended) > 0
        out[np.asarray(list(idx_a))] = has

    return out


def harmonize_chrom_names_to_reference(df, ref_chroms, chrom_col="chrom"):
    """
    Harmonizes chromosome names to reference set.
    Handles:
    1 <-> chr1 <-> Chr1
    """
    df = df.copy()
    df[chrom_col] = df[chrom_col].astype(str)

    ref_chroms = set(map(str, ref_chroms))
    cur = set(df[chrom_col])

    if len(cur & ref_chroms) > 0:
        return df

    def variants(x):
        x = str(x)
        out = [x]

        if x.startswith("chr"):
            core = x[3:]
            out += [core, "Chr" + core]
        elif x.startswith("Chr"):
            core = x[3:]
            out += [core, "chr" + core]
        else:
            out += ["chr" + x, "Chr" + x]

        return out

    mapping = {}

    for x in cur:
        found = None
        for v in variants(x):
            if v in ref_chroms:
                found = v
                break

        if found is not None:
            mapping[x] = found
        else:
            mapping[x] = x

    df[chrom_col] = df[chrom_col].map(mapping)

    new_overlap = len(set(df[chrom_col]) & ref_chroms)

    if new_overlap == 0:
        print("WARNING: could not harmonize chromosome names.")
        print("Example df chroms:", sorted(list(cur))[:10])
        print("Example ref chroms:", sorted(list(ref_chroms))[:10])
    else:
        print("Chromosome-name harmonization overlap:", new_overlap)

    return df


def to_bed8(df, label, name_prefix=None, score_col="score", strand_col=None):
    """
    Converts interval dataframe to BED8-like table:
    #chrom, chromStart, chromEnd, name, score, strand, thickStart, thickEnd
    """
    out = pd.DataFrame()
    out["#chrom"] = df["chrom"].astype(str)
    out["chromStart"] = df["start"].astype(int)
    out["chromEnd"] = df["end"].astype(int)

    if name_prefix is None:
        name_prefix = label

    out["name"] = [
        f"{i + 1}_{label}"
        for i in range(len(df))
    ]

    if score_col in df.columns:
        out["score"] = pd.to_numeric(df[score_col], errors="coerce").fillna(0).clip(0, 1000).astype(int)
    else:
        out["score"] = 1000

    if strand_col is not None and strand_col in df.columns:
        out["strand"] = df[strand_col].fillna(".").astype(str)
    else:
        out["strand"] = "."

    out["thickStart"] = out["chromStart"]
    out["thickEnd"] = out["chromEnd"]

    return out

def normalize_xentr_chrom(chrom):
    chrom = str(chrom)

    if chrom.startswith("Chr"):
        return chrom

    if chrom.startswith("chr"):
        return "Chr" + chrom[3:]

    # для обычных '1', '2', ..., '10'
    return "Chr" + chrom

tss = read_gtf_transcript_tss(
    genes_path_xenopus,
    protein_coding_only=False,   # для первого прохода лучше False
)

h3k4me1 = read_narrowpeak(h3k4me1_bed)
h3k4me3 = read_narrowpeak(h3k4me3_bed)
h3k9ac  = read_narrowpeak(h3k9ac_bed)
p300    = read_narrowpeak(p300_bed)
rnapii  = read_narrowpeak(rnapii_bed)

print("TSS:", tss.shape)
print("H3K4me1:", h3k4me1.shape)
print("H3K4me3:", h3k4me3.shape)
print("H3K9ac:", h3k9ac.shape)
print("p300:", p300.shape)
print("RNAPII:", rnapii.shape)

ref_chroms = p300["chrom"].unique()

tss = harmonize_chrom_names_to_reference(tss, ref_chroms, chrom_col="chrom")

# TSS из GTF
tss["chrom"] = tss["chrom"].apply(normalize_xentr_chrom)

# на всякий случай все peak tables тоже приводим к тому же стилю
for df in [h3k4me1, h3k4me3, h3k9ac, p300, rnapii]:
    df["chrom"] = df["chrom"].apply(normalize_xentr_chrom)

print("chrom overlap TSS/p300:", len(set(tss["chrom"]) & set(p300["chrom"])))
print("chrom overlap TSS/H3K4me3:", len(set(tss["chrom"]) & set(h3k4me3["chrom"])))

print("TSS chrom examples:", sorted(tss["chrom"].unique())[:10])
print("p300 chrom examples:", sorted(p300["chrom"].unique())[:10])

promoter_window_bp = 1000

promoters = make_tss_windows(
    tss,
    window_bp=promoter_window_bp,
)

print(promoters.head())
print(len(promoters))

print("TSS ∩ H3K4me3 chroms:", sorted(set(tss["chrom"]) & set(h3k4me3["chrom"])))
print("TSS ∩ RNAPII chroms:", sorted(set(tss["chrom"]) & set(rnapii["chrom"])))

print("promoters chrom examples:", sorted(promoters["chrom"].unique())[:10])
print("H3K4me3 chrom examples:", sorted(h3k4me3["chrom"].unique())[:10])

promoters["has_H3K4me3"] = overlap_any(promoters, h3k4me3)
promoters["has_RNAPII"] = overlap_any(promoters, rnapii)

active_promoters_h3k4me3 = promoters[
    promoters["has_H3K4me3"]
].copy()

active_promoters_strict = promoters[
    promoters["has_H3K4me3"] & promoters["has_RNAPII"]
].copy()

# score для BED: условно 1000 для active promoter
active_promoters_h3k4me3["score"] = 1000
active_promoters_strict["score"] = 1000

print("active promoters H3K4me3:", len(active_promoters_h3k4me3))
print("active promoters H3K4me3 + RNAPII:", len(active_promoters_strict))

active_promoters_h3k4me3_bed8 = to_bed8(
    active_promoters_h3k4me3,
    label="TssA1",
    score_col="score",
    strand_col="strand",
)

active_promoters_strict_bed8 = to_bed8(
    active_promoters_strict,
    label="TssA1",
    score_col="score",
    strand_col="strand",
)
active_promoters_h3k4me3_bed8.to_csv(
    f"{out_prefix}_active_promoters_H3K4me3.bed",
    sep="\t",
    index=False,
)

active_promoters_strict_bed8.to_csv(
    f"{out_prefix}_active_promoters_H3K4me3_RNAPII.bed",
    sep="\t",
    index=False,
)

enh = p300.copy()

enh["has_H3K4me1"] = overlap_any(enh, h3k4me1)
enh["has_H3K9ac"] = overlap_any(enh, h3k9ac)

enh_candidates = enh[
    enh["has_H3K4me1"] #& enh["has_H3K9ac"]
].copy()

print("p300 ∩ H3K4me1(∩ H3K9a) c:", len(enh_candidates))

tss_exclusion_window_bp = 2000

tss_exclusion = make_tss_windows(
    tss,
    window_bp=tss_exclusion_window_bp,
)

enh_candidates["near_TSS_2kb"] = overlap_any(
    enh_candidates,
    tss_exclusion,
)

active_distal_enhancers = enh_candidates[
    ~enh_candidates["near_TSS_2kb"]
].copy()

print("active distal enhancers:", len(active_distal_enhancers))

active_distal_enhancers_bed8 = to_bed8(
    active_distal_enhancers,
    label="EnhA1",
    score_col="score",
    strand_col=None,
)

active_distal_enhancers_bed8.to_csv(
    f"{out_prefix}_active_distal_enhancers_p300_H3K4me1_H3K9ac.bed",
    sep="\t",
    index=False,
)

regulatory_annotation_bed8 = pd.concat(
    [
        active_promoters_strict_bed8,
        active_distal_enhancers_bed8,
    ],
    ignore_index=True,
)

regulatory_annotation_bed8 = regulatory_annotation_bed8.sort_values(
    ["#chrom", "chromStart", "chromEnd"]
).reset_index(drop=True)

regulatory_annotation_bed8.to_csv(
    f"{out_prefix}_regulatory_annotation_TssA1_EnhA1.bed",
    sep="\t",
    index=False,
)

regulatory_annotation_bed8.head()

prom_tsv = active_promoters_strict_bed8.copy()
prom_tsv["feature_type"] = "active_promoter"
prom_tsv["state"] = "TssA1"

enh_tsv = active_distal_enhancers_bed8.copy()
enh_tsv["feature_type"] = "active_enhancer"
enh_tsv["state"] = "EnhA1"

regulatory_annotation_tsv = pd.concat(
    [prom_tsv, enh_tsv],
    ignore_index=True,
)

regulatory_annotation_tsv.to_csv(
    f"{out_prefix}_regulatory_annotation_TssA1_EnhA1.tsv",
    sep="\t",
    index=False,
)

regulatory_annotation_tsv.head()

"""#Загрузка файла с энхансерами и промоторами"""

regulatory_annotation_tsv = pd.read_csv(reg_path_xenopus, sep='\t')
promoters_for_fountains = regulatory_annotation_tsv[
    regulatory_annotation_tsv["feature_type"] == "active_promoter"
].copy()

enhancers_for_fountains = regulatory_annotation_tsv[
    regulatory_annotation_tsv["feature_type"] == "active_enhancer"
].copy()

promoters_for_fountains

enhancers_for_fountains2 = enhancers_for_fountains.copy()
enhancers_for_fountains2.columns = enhancers_for_fountains2.columns.str.strip()

# BED8 -> internal format
rename_map = {
    "#chrom": "chrom",
    "chromStart": "start",
    "chromEnd": "end",
    "score": "state_score",
}

enhancers_for_fountains2 = enhancers_for_fountains2.rename(
    columns={k: v for k, v in rename_map.items() if k in enhancers_for_fountains2.columns}
)

# если state нет, достаем его из name: например 15_EnhA1 -> EnhA1
if "state" not in enhancers_for_fountains2.columns:
    if "name" in enhancers_for_fountains2.columns:
        enhancers_for_fountains2["state"] = (
            enhancers_for_fountains2["name"]
            .astype(str)
            .str.replace(r"^\d+_", "", regex=True)
        )
    else:
        enhancers_for_fountains2["state"] = "EnhA1"

# обязательные типы
enhancers_for_fountains2["chrom"] = enhancers_for_fountains2["chrom"].astype(str)
enhancers_for_fountains2["start"] = enhancers_for_fountains2["start"].astype(int)
enhancers_for_fountains2["end"] = enhancers_for_fountains2["end"].astype(int)
enhancers_for_fountains2["feature_id"] = enhancers_for_fountains2.index

print(enhancers_for_fountains2.columns.tolist())
print(enhancers_for_fountains2.head())

promoters_for_fountains2 = promoters_for_fountains.copy()
promoters_for_fountains2.columns = promoters_for_fountains2.columns.str.strip()

promoters_for_fountains2 = promoters_for_fountains2.rename(
    columns={k: v for k, v in rename_map.items() if k in promoters_for_fountains2.columns}
)

# если state нет, достаем его из name: например 15_EnhA1 -> EnhA1
if "state" not in promoters_for_fountains2.columns:
    if "name" in promoters_for_fountains2.columns:
        promoters_for_fountains2["state"] = (
            promoters_for_fountains2["name"]
            .astype(str)
            .str.replace(r"^\d+_", "", regex=True)
        )
    else:
        promoters_for_fountains2["state"] = "TssA1"

# обязательные типы
promoters_for_fountains2["chrom"] = promoters_for_fountains2["chrom"].astype(str)
promoters_for_fountains2["start"] = promoters_for_fountains2["start"].astype(int)
promoters_for_fountains2["end"] = promoters_for_fountains2["end"].astype(int)

print(promoters_for_fountains2.columns.tolist())
print(promoters_for_fountains2.head())

"""#Загрузка фонтанов"""

flank_kb = 250
res = 5_000

results_df, failed_df, expected_raw = ft.process_fountains_batch(
    cool_path= mcool_path_xenopus,
    fountains_csv=fountains_path_xenopus,
    output_csv="fountain_fit_results.csv",
    failed_csv="fountain_fit_failed.csv",
    res=10_000,
    flank=flank_kb*1000,
    p0_kb=50,
    p_half_window_kb=40,
    fit_window_kb=180,
    diag_exclusion_kb=10,
    z_transform="oe",
    expected_nproc=4,
)

individual_Z_list, Z_stack, used_df, failed_df, expected_raw, exp_cache = (
    ft.collect_individual_fountain_Zs(
        cool_path = mcool_path_xenopus,
        fountains_csv=fountains_path_xenopus,
        res=res,
        flank=flank_kb*1000,
        z_transform="oe",
        expected_nproc=1,
        weight_col=None,      # <-- важно
        min_weight=None,
        require_full_window=True,
        base_shift_bp=-6000,
    )
)

"""# Работа с аннотированными энхансерами и промоторами


"""

fountains = ft.prepare_fountains_for_annotation(results_df)

enhancers_for_fountains2

enhancer_summary, enhancer_hits_at_base = ft.annotate_fountains_with_nearby_features(
    fountains_df=fountains,
    features_df=enhancers_for_fountains2,
    feature_name="enhancer",
    max_distance_bp=50_000,  # можно 0, 10_000, 20_000
    fountain_id_col="Fountain index",
    base_col="base_bp",
)

fountains_enh_annotated = fountains.merge(
    enhancer_summary,
    on=["Fountain index", "chrom", "base_bp"],
    how="left",
)

fountains_near_enhancer_50kb = fountains_enh_annotated[
    fountains_enh_annotated["nearest_enhancer_distance_bp"] <= 50_000
].copy()

promoter_hits_200kb, promoter_summary_200kb = ft.find_features_in_window_around_fountains(
    fountains_df=fountains_near_enhancer_50kb,
    features_df=promoters_for_fountains2,
    feature_name="promoter",
    window_bp=200_000,
    fountain_id_col="Fountain index",
    base_col="base_bp",
)

fountains_near_enhancer_with_promoters = fountains_near_enhancer_50kb.merge(
    promoter_summary_200kb,
    on=["Fountain index", "chrom", "base_bp"],
    how="left",
)

fountains_with_promoters = results_df.merge(
    promoter_summary_200kb,
    on=["Fountain index", "chrom", "base_bp"],
    how="left",
)

fountains_near_enhancer_with_promoters

fountains_enh_annotated

"""#Ориентация фонтана по расположению промоторов"""

oriented_df = ft.make_nearest_promoter_orientation_table(
    fountains_df=results_df,
    promoter_hits_df=promoter_hits_200kb,
    fountain_id_col="Fountain index",
    chrom_col="chrom",
    base_col="base_bp",
    feature_name="promoter",
)

Z_promoter_right, oriented_df_used = ft.orient_fountain_stack_promoter_right(
    Z_stack=Z_stack,
    oriented_df=oriented_df,
    drop_without_promoter=True,
)

if "Fountain Score" in oriented_df_used.columns:
    weights = oriented_df_used["Fountain Score"].to_numpy(dtype=float)
else:
    weights = None

aggregate_Z_promoter_right = ft.weighted_nanmean_stack(
    Z_promoter_right,
    weights=None,
)

fig, ax, Z_smooth, levels = ft.plot_smoothed_hic_contours(
    aggregate_Z_promoter_right,
    res=5_000,
    sigma=1.2,
    cmap="coolwarm",
    vmin=0.8,
    vmax=1.2,
    linecolor="blue",
    linewidth=1.5,
    show_image=True,
    levels=[1.2, 1.4, 1.6],
    restrict_contours_to_largest_component=True,
    component_baseline=1.1,
    component_from_smoothed=True,
    component_connectivity=2,
    component_diag_exclusion_kb=10,
    show_component_boundary=True,
    shade_component=False,
    return_component_info=True,
)
plt.show()

asym_res = ft.compute_promoter_side_asymmetry(
    aggregate_Z_promoter_right,
    res=res,
    window_kb=flank_kb,
    diag_exclusion_kb=10,
    baseline=1.05,
    use_positive_enrichment=True,
    smooth_sigma=1.2,
    largest_component_only=True,
    component_connectivity=2,
    symmetrize_component_mask=True,
)

print(asym_res)
print("Promoter-side asymmetry:", asym_res["asymmetry"])
print("COM shift, kb:", asym_res["u_com_kb"])
print("Normalized COM shift:", asym_res["u_com_normalized"])

oriented_df_count = ft.make_promoter_count_orientation_table(
    fountains_df=results_df,   # важно: тот df, который соответствует Z_stack
    promoter_hits_df=promoter_hits_200kb,  # уже промоторы в окне ±200 kb
    fountain_id_col="Fountain index",
    chrom_col="chrom",
    base_col="base_bp",
    feature_name="promoter",
    tie_strategy="no_flip",  # или "nearest"
)
Z_promoter_count_right, oriented_df_count_used = ft.orient_fountain_stack_promoter_right(
    Z_stack=Z_stack,
    oriented_df=oriented_df_count,
    drop_without_promoter=True,
)

print("fountains total:", len(results_df))
print("with promoter ±200 kb:", oriented_df_count["has_promoter_200kb"].sum())
print("flipped:", oriented_df_count["flip_for_promoter_right"].sum())

print(
    oriented_df_used[
        [
            "Fountain index",
            "chrom",
            "base_bp",
            "nearest_promoter_mid_bp",
            "promoter_delta_bp",
            "flip_for_promoter_right",
            "promoter_delta_oriented_bp",
        ]
    ].head()
)

if "Fountain Score" in oriented_df_used.columns:
    weights = oriented_df_used["Fountain Score"].to_numpy(dtype=float)
else:
    weights = None

aggregate_Z_promoter_right = ft.weighted_nanmean_stack(
    Z_promoter_count_right[0:50],
    weights=None,
)

fig, ax, Z_smooth, levels = ft.plot_smoothed_hic_contours(
    aggregate_Z_promoter_right,
    res=5_000,
    sigma=1.2,
    cmap="coolwarm",
    vmin=0.8,
    vmax=1.2,
    linecolor="blue",
    linewidth=1.5,
    show_image=True,
    levels=[1.07]
)
plt.show()

asym_res = ft.compute_promoter_side_asymmetry(
    aggregate_Z_promoter_right,
    res=res,
    window_kb=flank_kb,
    diag_exclusion_kb=10,
    baseline=1.05,
    use_positive_enrichment=True,
    smooth_sigma=1.2,
    largest_component_only=True,
    component_connectivity=2,
    symmetrize_component_mask=True,
)

print(asym_res)
print("Promoter-side asymmetry:", asym_res["asymmetry"])
print("COM shift, kb:", asym_res["u_com_kb"])
print("Normalized COM shift:", asym_res["u_com_normalized"])

aggregate_Z, aggregate_info, used_df, failed_df, expected_raw = ft.build_weighted_aggregate_fountain(
    cool_path = mcool_path_xenopus,
    fountains_csv=fountains_path_xenopus,
    flank=flank_kb,
    res=res,
    weight_col=None,
    z_transform="oe",
    expected_nproc=4,
    min_weight=0,
    require_full_window=True,
)

oriented_df = ft.make_nearest_promoter_orientation_table(
    fountains_df=results_df,                 # именно used_df
    promoter_hits_df=promoter_hits_200kb,
    fountain_id_col="Fountain index",
    chrom_col="chrom",
    base_col="base_bp",
    feature_name="promoter",
)

# ------------------------------------------------------------
# 2. Ориентируем все индивидуальные фонтаны:
#    после этого ближайший promoter должен быть справа
# ------------------------------------------------------------

Z_promoter_right, oriented_df_used = ft.orient_fountain_stack_promoter_right(
    Z_stack=Z_stack,
    oriented_df=oriented_df,
    drop_without_promoter=True,
)

# sanity check
print("N oriented fountains:", len(oriented_df_used))
print("All have promoter:", oriented_df_used["has_promoter_200kb"].all())
print(
    "Fraction with oriented promoter distance < 0:",
    np.mean(oriented_df_used["promoter_delta_oriented_bp"] < 0)
)

# 3. Расстояние до ближайшего промотора в kb
# ------------------------------------------------------------

promoter_dist_kb = oriented_df_used["promoter_delta_oriented_bp"].to_numpy(dtype=float) / 1000.0

# окно у тебя было 200 kb, поэтому разумно так:
bin_edges_kb = [0,10,20,30,40,50,60,100,150,200]   # 0,10,20,...,200

# сюда будем складывать результаты
asym_rows = []

# ------------------------------------------------------------
# 4. Цикл по бинам
# ------------------------------------------------------------

for i in range(len(bin_edges_kb) - 1):
    lo = bin_edges_kb[i]
    hi = bin_edges_kb[i + 1]

    # полуинтервалы [lo, hi), кроме последнего бина
    if i < len(bin_edges_kb) - 2:
        mask = (promoter_dist_kb >= lo) & (promoter_dist_kb < hi)
    else:
        mask = (promoter_dist_kb >= lo) & (promoter_dist_kb <= hi)

    n_bin = int(mask.sum())

    print(f"Bin {lo:>3.0f}-{hi:<3.0f} kb : N = {n_bin}")

    # можно пропускать слишком малые выборки
    if n_bin < 10:
        print("  skipped: too few fountains")
        continue

    Z_bin = Z_promoter_right[mask]
    df_bin = oriented_df_used.loc[mask].copy()

    # --------------------------------------------------------
    # 4a. Строим агрегат
    # без взвешивания
    # --------------------------------------------------------
    aggregate_Z_bin = np.nanmean(Z_bin, axis=0)

    # --------------------------------------------------------
    # 4b. Считаем асимметрию
    # --------------------------------------------------------
    asym_res = ft.compute_promoter_side_asymmetry(
        aggregate_Z=aggregate_Z_bin,
        res=res,
        window_kb=flank_kb,
        diag_exclusion_kb=10,
        baseline=1.05,
        use_positive_enrichment=True,
        smooth_sigma=1.2,
        largest_component_only=True,
        component_connectivity=2,
        symmetrize_component_mask=True
    )

    asym_val = asym_res["asymmetry"]

    # --------------------------------------------------------
    # 4c. Сохраняем результат
    # --------------------------------------------------------
    asym_rows.append({
        "bin_start_kb": lo,
        "bin_end_kb": hi,
        "bin_center_kb": 0.5 * (lo + hi),
        "n_fountains": n_bin,
        "asymmetry": asym_val,
        "u_com_kb": asym_res["u_com_kb"],
        "u_com_normalized": asym_res["u_com_normalized"],
    })

    fig, ax, Z_smooth, levels = ft.plot_smoothed_hic_contours(
      aggregate_Z_bin,
      res=5_000,
      sigma=1.2,
      cmap="coolwarm",
      vmin=0.8,
      vmax=1.2,
      linecolor="blue",
      linewidth=1.5,
      show_image=True,
      levels=[1.15]
      )
    plt.show()

asym_df = pd.DataFrame(asym_rows)
asym_df

plt.figure(figsize=(6, 4.5))

plt.scatter(
    asym_df["bin_center_kb"],
    asym_df["asymmetry"],
    s=50,
)

plt.plot(
    asym_df["bin_center_kb"],
    asym_df["asymmetry"],
)

plt.axhline(0, color="gray", linestyle="--", linewidth=0.8)

plt.xlabel("Nearest promoter distance, kb")
plt.ylabel("Promoter-side asymmetry")
plt.title("Promoter distance vs fountain asymmetry")
plt.tight_layout()
plt.show()

fountains_df_for_stack = results_df.copy()
# если у тебя Z_stack строился по used_df, тогда:
# fountains_df_for_stack = used_df.copy()

fountains_df_for_stack = fountains_df_for_stack.copy()
fountains_df_for_stack.columns = fountains_df_for_stack.columns.str.strip()

print("len(Z_stack) =", len(Z_stack))
print("len(fountains_df_for_stack) =", len(fountains_df_for_stack))
assert len(Z_stack) == len(fountains_df_for_stack), "Z_stack и fountains_df_for_stack не согласованы"

# добавим явный индекс в стеке
fountains_df_for_stack = fountains_df_for_stack.reset_index(drop=True)
fountains_df_for_stack["stack_idx"] = np.arange(len(fountains_df_for_stack))

hits = promoter_hits_200kb.copy()
hits.columns = hits.columns.str.strip()

print(hits.columns.tolist())

hits["promoter_mid_bp"] = hits["promoter_center"].astype(float)

fountains_df_for_stack = fountains_df_for_stack.copy()
fountains_df_for_stack.columns = fountains_df_for_stack.columns.str.strip()

# проверка
print("hits columns:", hits.columns.tolist())
print("fountains columns:", fountains_df_for_stack.columns.tolist())

# ------------------------------------------------------------
# merge только по Fountain index
# ------------------------------------------------------------

expanded_hits = hits.merge(
    fountains_df_for_stack[["Fountain index", "stack_idx", "base_bp"]],
    on="Fountain index",
    how="inner",
    suffixes=("", "_stack"),
)

# если base_bp уже был в hits, pandas мог создать base_bp_stack;
# нам нужна база фонтана из fountains_df_for_stack
if "base_bp_stack" in expanded_hits.columns:
    expanded_hits["base_bp"] = expanded_hits["base_bp_stack"]

print("N promoter hits after merge:", len(expanded_hits))
expanded_hits.head()

promoter_oriented_Z_list = []
promoter_dist_kb_list = []
promoter_meta_rows = []

for _, row in expanded_hits.iterrows():
    stack_idx = int(row["stack_idx"])
    Z_i = np.asarray(Z_stack[stack_idx], dtype=float)

    base_bp = float(row["base_bp"])
    prom_bp = float(row["promoter_mid_bp"])

    delta_bp = prom_bp - base_bp   # signed distance
    dist_kb = abs(delta_bp) / 1000.0

    # ориентируем так, чтобы именно этот promoter оказался справа
    if delta_bp < 0:
        Z_oriented = Z_i[::-1, ::-1]
        delta_oriented_bp = -delta_bp
        flipped = True
    else:
        Z_oriented = Z_i.copy()
        delta_oriented_bp = delta_bp
        flipped = False

    promoter_oriented_Z_list.append(Z_oriented)
    promoter_dist_kb_list.append(delta_oriented_bp / 1000.0)

    promoter_meta_rows.append({
        "Fountain index": row["Fountain index"],
        "base_bp": row["base_bp"],
        "stack_idx": stack_idx,
        "promoter_mid_bp": prom_bp,
        "promoter_delta_bp": delta_bp,
        "promoter_dist_kb": delta_oriented_bp / 1000.0,
        "flipped_for_this_promoter": flipped,
    })

promoter_oriented_Z = np.asarray(promoter_oriented_Z_list, dtype=float)
promoter_meta_df = pd.DataFrame(promoter_meta_rows)

print("promoter_oriented_Z shape:", promoter_oriented_Z.shape)
print(promoter_meta_df.head())

bin_edges_kb = np.arange(0, 201, 10)

asym_rows = []
flank_kb = 200   # если окно ±200 kb
res = 5_000

for i in range(len(bin_edges_kb) - 1):
    lo = bin_edges_kb[i]
    hi = bin_edges_kb[i + 1]

    if i < len(bin_edges_kb) - 2:
        mask = (
            (promoter_meta_df["promoter_dist_kb"] >= lo) &
            (promoter_meta_df["promoter_dist_kb"] < hi)
        )
    else:
        mask = (
            (promoter_meta_df["promoter_dist_kb"] >= lo) &
            (promoter_meta_df["promoter_dist_kb"] <= hi)
        )

    n_bin = int(mask.sum())
    print(f"Bin {lo:>3.0f}-{hi:<3.0f} kb: N_promoters = {n_bin}")

    if n_bin < 10:
        print("  skipped: too few promoter-oriented instances")
        continue

    Z_bin = promoter_oriented_Z[mask.to_numpy()]

    # агрегируем
    aggregate_Z_bin = np.nanmean(Z_bin, axis=0)

    # считаем асимметрию
    asym_res = ft.compute_promoter_side_asymmetry(
        aggregate_Z=aggregate_Z_bin,
        res=res,
        window_kb=flank_kb,
        diag_exclusion_kb=10,
        baseline=1.0,
        use_positive_enrichment=True,
        smooth_sigma=1.2,
    )

    asym_val = asym_res["asymmetry"]

    asym_rows.append({
        "bin_start_kb": lo,
        "bin_end_kb": hi,
        "mean_distance_kb": float(promoter_meta_df.loc[mask, "promoter_dist_kb"].mean()),
        "n_promoters": n_bin,
        "n_unique_fountains": int(promoter_meta_df.loc[mask, "Fountain index"].nunique()),
        "asymmetry": asym_val,
        "u_com_kb": asym_res["u_com_kb"],
        "u_com_normalized": asym_res["u_com_normalized"],
    })

    # --------------------------------------------------------
    # картинка
    # --------------------------------------------------------
    extent = [-flank_kb, flank_kb, flank_kb, -flank_kb]

    plt.figure(figsize=(5.5, 5.0))
    plt.imshow(
        aggregate_Z_bin,
        origin="upper",
        extent=extent,
        cmap="coolwarm",
        vmin=0.8,
        vmax=1.15,
        interpolation="nearest",
        aspect="equal",
    )

    plt.axline((0, 0), slope=1, linestyle="--", linewidth=0.8, color="gray", alpha=0.5)
    plt.axline((0, 0), slope=-1, linestyle=":", linewidth=0.8, color="gray", alpha=0.5)

    plt.xlabel("Distance from fountain base, kb")
    plt.ylabel("Distance from fountain base, kb")
    plt.title(
        f"Promoter distance {lo:.0f}-{hi:.0f} kb\n"
        f"Nprom={n_bin}, Nfount={promoter_meta_df.loc[mask, 'Fountain index'].nunique()}, asym={asym_val:.4f}"
    )
    plt.colorbar(label="O/E")
    plt.tight_layout()
    plt.show()

asym_df = pd.DataFrame(asym_rows).sort_values("mean_distance_kb").reset_index(drop=True)
asym_df

plt.figure(figsize=(6, 4.5))

plt.scatter(
    (asym_df["bin_start_kb"]+asym_df["bin_end_kb"])/2,
    asym_df["asymmetry"],
    s=60,
)

plt.plot(
    asym_df["mean_distance_kb"],
    asym_df["asymmetry"],
)


plt.axhline(0, color="gray", linestyle="--", linewidth=0.8)

plt.xlabel("Mean promoter distance, kb")
plt.ylabel("Promoter-side asymmetry")
plt.tight_layout()
plt.show()

"""#Рисуем самые асиммметричные фонтаны"""

Z_stack_used = Z_stack[0:100]
fountains_df_for_stack = results_df.copy()[0:100]
# или used_df.copy(), если именно он соответствует Z_stack

fountains_df_for_stack = fountains_df_for_stack.copy().reset_index(drop=True)
fountains_df_for_stack.columns = fountains_df_for_stack.columns.str.strip()
fountains_df_for_stack["stack_idx"] = np.arange(len(fountains_df_for_stack))

print("len(Z_stack) =", len(Z_stack_used))
print("len(fountains_df_for_stack) =", len(fountains_df_for_stack))
assert len(Z_stack_used) == len(fountains_df_for_stack), "Z_stack и fountains_df_for_stack не согласованы"

ind_rows = []

for i, Z_i in enumerate(Z_stack_used):
    asym_res =  ft.compute_promoter_side_asymmetry(
        aggregate_Z=np.asarray(Z_i, dtype=float),
        res=5_000,
        window_kb=200,
        diag_exclusion_kb=10,
        baseline=1.0,
        use_positive_enrichment=True,
        smooth_sigma=1.2,
    )

    meta_row = fountains_df_for_stack.iloc[i]

    ind_rows.append({
        "stack_idx": i,
        "Fountain index": meta_row["Fountain index"],
        "chrom": meta_row["chrom"] if "chrom" in meta_row.index else np.nan,
        "base_bp": meta_row["base_bp"] if "base_bp" in meta_row.index else np.nan,
        "asymmetry": asym_res["asymmetry"],
        "abs_asymmetry": abs(asym_res["asymmetry"]) if np.isfinite(asym_res["asymmetry"]) else np.nan,
        "u_com_kb": asym_res["u_com_kb"],
        "u_com_normalized": asym_res["u_com_normalized"],
    })

ind_asym_df = pd.DataFrame(ind_rows)
ind_asym_df = ind_asym_df.sort_values("abs_asymmetry", ascending=False).reset_index(drop=True)

ind_asym_df.head(10)

prom_hits = promoter_hits_200kb.copy()
prom_hits.columns = prom_hits.columns.str.strip()

# Попробуем угадать координаты промотора
prom_hits["feature_mid_bp"] = prom_hits["promoter_center"]

# merge с stack_idx
prom_hits = prom_hits.merge(
    fountains_df_for_stack[["Fountain index", "base_bp", "stack_idx"]],
    on="Fountain index",
    how="inner",
    suffixes=("", "_fount"),
)

# если после merge появилась base_bp_fount, используем её
if "base_bp_fount" in prom_hits.columns:
    prom_hits["base_bp_use"] = prom_hits["base_bp_fount"].astype(float)
else:
    prom_hits["base_bp_use"] = prom_hits["base_bp"].astype(float)

prom_hits["delta_bp"] = prom_hits["feature_mid_bp"] - prom_hits["base_bp_use"]
prom_hits["delta_kb"] = prom_hits["delta_bp"] / 1000.0

enhancer_hits_at_base

enh_hits = enhancer_hits_at_base.copy()
enh_hits.columns = enh_hits.columns.str.strip()

# midpoint
enh_hits["feature_mid_bp"] = (enh_hits["enhancer_start"]+enh_hits["enhancer_end"])/2

# если есть start/end, используем их для полоски
enh_hits["feature_start_bp"] = enh_hits["enhancer_start"].astype(float)
enh_hits["feature_end_bp"] = enh_hits["enhancer_end"].astype(float)

enh_hits = enh_hits.merge(
    fountains_df_for_stack[["Fountain index", "base_bp", "stack_idx"]],
    on="Fountain index",
    how="inner",
    suffixes=("", "_fount"),
)

enh_hits["base_bp_use"] = enh_hits["fountain_base_bp"].astype(float)

enh_hits["delta_start_kb"] = (enh_hits["feature_start_bp"] - enh_hits["base_bp_use"]) / 1000.0
enh_hits["delta_end_kb"]   = (enh_hits["feature_end_bp"]   - enh_hits["base_bp_use"]) / 1000.0
enh_hits["delta_mid_kb"]   = (enh_hits["feature_mid_bp"]   - enh_hits["base_bp_use"]) / 1000.0

top_n = 100
top_df = ind_asym_df.head(top_n).copy()
top_df

flank_kb = 200
extent = [-flank_kb, flank_kb, flank_kb, -flank_kb]

for _, row in top_df.iterrows():
    stack_idx = int(row["stack_idx"])
    fountain_id = row["Fountain index"]
    asym = row["asymmetry"]

    Z_i = np.asarray(Z_stack[stack_idx], dtype=float)

    prom_i = prom_hits[prom_hits["stack_idx"] == stack_idx].copy()
    enh_i  = enh_hits[enh_hits["stack_idx"] == stack_idx].copy()
    if len(enh_i)>0 and len(prom_i)>0:
      plt.figure(figsize=(6.0, 5.5))

      plt.imshow(
          Z_i,
          origin="upper",
          extent=extent,
          cmap="coolwarm",
          vmin=0.8,
          vmax=1.15,
          interpolation="nearest",
          aspect="equal",
          zorder=0,
      )

      # диагонали
      plt.axline((0, 0), slope=1, linestyle="--", linewidth=0.8, color="gray", alpha=0.5, zorder=5)
      plt.axline((0, 0), slope=-1, linestyle=":", linewidth=0.8, color="gray", alpha=0.5, zorder=5)

      # --------------------------------------------------------
      # энхансеры: полоски вдоль диагонали y=x
      # --------------------------------------------------------
      for _, e in enh_i.iterrows():
          x0 = float(e["delta_start_kb"])
          x1 = float(e["delta_end_kb"])

          # ограничим окно на всякий случай
          x0 = max(x0, -flank_kb)
          x1 = min(x1, flank_kb)

          plt.plot(
              [x0, x1],
              [x0, x1],
              linewidth=50,
              alpha=1,
              solid_capstyle="butt",
              zorder=20,
              color='black'
          )

      # --------------------------------------------------------
      # промоторы: крестики на диагонали y=x
      # --------------------------------------------------------
      if len(prom_i) > 0:
          x_prom = prom_i["delta_kb"].to_numpy(dtype=float)
          y_prom = x_prom.copy()

          plt.scatter(
              x_prom,
              y_prom,
              marker="x",
              s=70,
              linewidths=1.8,
              zorder=30,
          )

      plt.xlabel("Distance from fountain base, kb")
      plt.ylabel("Distance from fountain base, kb")
      plt.title(
          f"Fountain {fountain_id}\n"
          f"asym={asym:.4f}, |asym|={abs(asym):.4f}"
      )
      plt.colorbar(label="O/E")
      plt.tight_layout()
      plt.show()



"""#Гистограмма энхансеров относительно фонтанов"""

enhancers_for_fountains2

enhancer_fountain_hits_300 = ft.find_enhancers_near_fountains(
    fountains_df=fountains,
    enhancers_df=enhancers_for_fountains2,
    max_enhancer_distance_bp=300_000,
    fountain_id_col="Fountain index",
    base_col="base_bp",
)

enhancer_fountain_hits_60 = ft.find_enhancers_near_fountains(
    fountains_df=fountains,
    enhancers_df=enhancers_for_fountains2,
    max_enhancer_distance_bp=60_000,
    fountain_id_col="Fountain index",
    base_col="base_bp",
)

segments, density, edges, centers = ft.make_enhancer_density_segments(
    enhancer_hits=enhancer_fountain_hits_300,
    plot_window_kb=200,
    bin_width_kb=5,
    use_intervals=True,
    fountain_id_col="Fountain index",
    enhancer_id_col="enhancer_feature_id",
    start_col="enhancer_rel_start_kb",
    end_col="enhancer_rel_end_kb",
    center_col="enhancer_rel_center_kb",
)

df = pd.DataFrame({
    "bin_left_kb": edges[:-1],
    "bin_right_kb": edges[1:],
    "bin_center_kb": centers,
    "enhancer_density": density,
})

fit_enh, fig, ax = ft.fit_enhancer_density_gaussian(
    enhancer_hits=enhancer_fountain_hits_300,
    plot_window_kb=120,
    bin_width_kb=5,
    use_intervals=False,
    title="Enhancer distribution around fountain bases",
)

print(
    f"mu = {fit_enh['mu_kb']:.2f} "
    f"± {fit_enh['mu_se_kb']:.2f} kb"
)

print(
    f"sigma = {fit_enh['sigma_kb']:.2f} "
    f"± {fit_enh['sigma_se_kb']:.2f} kb"
)

print(f"R² = {fit_enh['r_squared']:.3f}")

plt.savefig(
    "enhancer_distribution_gaussian_fit.pdf",
    bbox_inches="tight",
)

plt.show()

"""#Фонтаны вблизи и вдали от энхансеров"""

res = 5_000
flank = 300_000
weight_col = "Fountain Score"
z_transform = "oe"
expected_nproc = 4
agg_with_enhancer_Z, info_with_enhancer, used_with_enhancer, failed_with_enhancer, expected_raw_with = (
    ft.build_weighted_aggregate_fountain(
        cool_path=mcool_path_xenopus,
        fountains_df=fountains_near_enhancer_50kb,
        flank=flank,
        res=res,
        weight_col=weight_col,
        z_transform=z_transform,
        expected_nproc=expected_nproc,
        min_weight=0,
        require_full_window=True,
    )
)

fountains_without_enhancer_at_50kb = results_df[~results_df['Fountain index'].isin(fountains_near_enhancer_50kb['Fountain index'])]

agg_without_enhancer_Z, info_without_enhancer, used_without_enhancer, failed_without_enhancer, expected_raw_without = (
    ft.build_weighted_aggregate_fountain(
        cool_path=mcool_path_xenopus,
        fountains_df=fountains_without_enhancer_at_50kb,
        flank=flank,
        res=res,
        weight_col=weight_col,
        z_transform=z_transform,
        expected_nproc=expected_nproc,
        min_weight=0,
        require_full_window=True,
    )
)

(fig_with, ax_with), (fig_without, ax_without), enh_density = (
    ft.plot_enhancer_vs_no_enhancer_separate(
        agg_with=agg_with_enhancer_Z,
        agg_without=agg_without_enhancer_Z,
        enhancer_hits_with=enhancer_fountain_hits_60,
        enhancer_hits_without=enhancer_fountain_hits_300,
        res=5_000,
        output_png_with="aggregate_with_enhancer_density.pdf",
        output_png_without="aggregate_without_enhancer.pdf",
        show_enhancer_density_colorbar=False
    )
)



"""#Корреляции между скором и количеством фонтанов"""

enhancer_fountain_hits_60

from scipy.stats import linregress
from scipy.stats import spearmanr, pearsonr

enh_50kb_summary = (
    enhancer_fountain_hits_60
    .query("enhancer_distance_to_base_bp <= 50000")
    .groupby("Fountain index", as_index=False)
    .agg(
        **{
            "Fountain Score": ("Fountain Score", "first"),
            "n_enhancers_50kb": ("enhancer_feature_id", "nunique"),
        }
    )
    .sort_values("Fountain Score", ascending=False)
    .reset_index(drop=True)
)
print(enh_50kb_summary)

score_by_enh_n = (
    enh_50kb_summary
    .groupby("n_enhancers_50kb", as_index=False)
    .agg(
        mean_score=("Fountain Score", "mean"),
        std_score=("Fountain Score", "std"),
        n_fountains=("Fountain Score", "count"),
    )
)
print(score_by_enh_n)

df_corr = enh_50kb_summary[
    ["n_enhancers_50kb", "Fountain Score"]
].dropna().copy()

x = df_corr["n_enhancers_50kb"]
y = df_corr["Fountain Score"]

rho_spearman, p_spearman = spearmanr(x, y)
r_pearson, p_pearson = pearsonr(x, y)

print(f"Spearman rho = {rho_spearman:.3f}, p = {p_spearman:.3g}")
print(f"Pearson r = {r_pearson:.3f}, p = {p_pearson:.3g}")
print(f"n fountains = {len(df_corr)}")

# фильтруем только надежные группы
plot_df_filt = score_by_enh_n[score_by_enh_n["n_fountains"] >= 2].copy()

x = plot_df_filt["n_enhancers_50kb"].to_numpy(dtype=float)
y = plot_df_filt["mean_score"].to_numpy(dtype=float)
n = plot_df_filt["n_fountains"].to_numpy(dtype=int)

# линейный тренд по средним значениям
lin = linregress(x, y)

x_line = np.linspace(x.min(), x.max(), 200)
y_line = lin.intercept + lin.slope * x_line


plot_df = plot_df_filt

plt.figure(figsize=(5, 5))

plt.errorbar(
    plot_df["n_enhancers_50kb"],
    plot_df["mean_score"],
    yerr=plot_df["std_score"],
    fmt="o",
    capsize=5,
    capthick=1.5,
    elinewidth=1.5,
    markersize=10,
    linewidth=2,
    color='red',
    ecolor = 'black'
)

# линейный тренд
plt.plot(
    x_line,
    y_line,
    linewidth=2,
    alpha=0.9,
    label=(
        f"Linear trend: slope={lin.slope:.3f},\n"
        f"R²={lin.rvalue**2:.2f}, p={lin.pvalue:.3g}"
    ),
    linestyle='dashed', color='black',
    zorder=2,
)



plt.xlabel("Number of enhancers within 50 kb", fontsize=13)
plt.ylabel("Mean fountain score", fontsize=13)
plt.legend(frameon=False, fontsize=10)

plt.xticks(plot_df["n_enhancers_50kb"])
plt.xlim((0,10))

plt.tight_layout()
plt.show()

plot_df_filt

"""#Построение фонтана, выровненного относительно энхансеров"""

enhancer_fountain_hits = ft.find_enhancers_near_fountains(
    fountains_df=fountains_near_enhancer_50kb,
    enhancers_df=enhancers_for_fountains2,
    max_enhancer_distance_bp=50_000,
    fountain_id_col="Fountain index",
    base_col="base_bp",
)

print(enhancer_fountain_hits.shape)
enhancer_fountain_hits.head()

nearest_enhancer_per_fountain = ft.select_nearest_enhancer_per_fountain(
    enhancer_fountain_hits,
    fountain_id_col="Fountain index",
)

nearest_enhancer_per_fountain.to_csv(
    "nearest_enhancer_per_fountain.csv",
    index=False,
)

nearest_enhancer_per_fountain

enh_aligned_Z, enh_aligned_info, enh_aligned_used, enh_aligned_failed, enh_expected_raw = (
    ft.build_enhancer_aligned_aggregate_fountain(
        cool_path=mcool_path_xenopus,
        nearest_enhancer_per_fountain=nearest_enhancer_per_fountain,
        flank=300_000,
        res=5_000,
        weight_col="Fountain Score",
        z_transform="oe",
        expected_nproc=4,
        min_weight=0,
        require_full_window=True,
    )
)

enh_aligned_info

np.save("enhancer_aligned_aggregate_Z.npy", enh_aligned_Z)

enh_aligned_used.to_csv(
    "enhancer_aligned_aggregate_used.csv",
    index=False,
)

enh_aligned_failed.to_csv(
    "enhancer_aligned_aggregate_failed.csv",
    index=False,
)

fig, ax = ft.plot_enhancer_aligned_aggregate(
    enh_aligned_Z,
    res=5_000,
    vmin=0.5,
    vmax=1.6,
    #title=f"Enhancer-aligned aggregate, n={enh_aligned_info['n_used']}",
    title="",
    output_png="enhancer_aligned_aggregate.png",
)

plt.show()

fig, ax = ft.plot_aggregate_fountain(
    aggregate_Z,
    fit_agg,
    fit_cache,
    vmin=0.5,
    vmax=1.6
)

plt.show()